/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include "HubPort.hpp"
#include "AlphaBlendingImpl.hpp"
#include "AlphaBlendingImplFactory.hpp"
#include "AlphaBlendingInternal.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

using kurento::KurentoException;

namespace kurento
{

MediaObjectImpl *AlphaBlendingImplFactory::createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const
{
  kurento::JsonSerializer s (false);
  AlphaBlendingConstructor constructor;

  s.JsonValue = params;
  constructor.Serialize (s);

  return createObject (conf, constructor.getMediaPipeline() );
}

void
AlphaBlendingImpl::invoke (std::shared_ptr<MediaObjectImpl> obj, const std::string &methodName, const Json::Value &params, Json::Value &response)
{
  if (methodName == "setMaster") {
    kurento::JsonSerializer s (false);
    AlphaBlendingMethodSetMaster method;

    s.JsonValue = params;
    method.Serialize (s);

    method.invoke (std::dynamic_pointer_cast<AlphaBlending> (obj) );
    return;
  }

  if (methodName == "setPortProperties") {
    kurento::JsonSerializer s (false);
    AlphaBlendingMethodSetPortProperties method;

    s.JsonValue = params;
    method.Serialize (s);

    method.invoke (std::dynamic_pointer_cast<AlphaBlending> (obj) );
    return;
  }

  HubImpl::invoke (obj, methodName, params, response);
}

bool
AlphaBlendingImpl::connect (const std::string &eventType, std::shared_ptr<EventHandler> handler)
{

  return HubImpl::connect (eventType, handler);
}

void
AlphaBlendingImpl::Serialize (JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    try {
      Json::Value v (getId() );

      serializer.JsonValue = v;
    } catch (std::bad_cast &e) {
    }
  } else {
    throw KurentoException (MARSHALL_ERROR,
                            "'AlphaBlendingImpl' cannot be deserialized as an object");
  }
}
} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::AlphaBlendingImpl> &object, JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    if (object) {
      object->Serialize (serializer);
    }
  } else {
    std::shared_ptr<kurento::MediaObjectImpl> aux;
    aux = kurento::AlphaBlendingImplFactory::getObject (JsonFixes::getString(serializer.JsonValue) );
    object = std::dynamic_pointer_cast<kurento::AlphaBlendingImpl> (aux);
  }
}

void
Serialize (std::shared_ptr<kurento::AlphaBlending> &object, JsonSerializer &serializer)
{
  std::shared_ptr<kurento::AlphaBlendingImpl> aux = std::dynamic_pointer_cast<kurento::AlphaBlendingImpl> (object);

  Serialize (aux, serializer);
  object = std::dynamic_pointer_cast <kurento::AlphaBlending> (aux);
}

} /* kurento */