/* Autogenerated with kurento-module-creator */

#ifndef __DISPATCHER_IMPL_FACTORY_HPP__
#define __DISPATCHER_IMPL_FACTORY_HPP__

#include "DispatcherImpl.hpp"
#include "HubImplFactory.hpp"
#include <Factory.hpp>
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{

class DispatcherImplFactory : public virtual HubImplFactory
{
public:
  DispatcherImplFactory() = default;

  std::string getName() const override {
    return "Dispatcher";
  };

private:

  MediaObjectImpl *createObjectPointer (
      const boost::property_tree::ptree &conf,
      const Json::Value &params) const override;

  MediaObjectImpl *createObject (const boost::property_tree::ptree &conf, std::shared_ptr<MediaPipeline> mediaPipeline) const;
};

} /* kurento */

#endif /*  __DISPATCHER_IMPL_FACTORY_HPP__ */
