/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include "HubPort.hpp"
#include "DispatcherOneToManyImpl.hpp"
#include "DispatcherOneToManyImplFactory.hpp"
#include "DispatcherOneToManyInternal.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

using kurento::KurentoException;

namespace kurento
{

MediaObjectImpl *DispatcherOneToManyImplFactory::createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const
{
  kurento::JsonSerializer s (false);
  DispatcherOneToManyConstructor constructor;

  s.JsonValue = params;
  constructor.Serialize (s);

  return createObject (conf, constructor.getMediaPipeline() );
}

void
DispatcherOneToManyImpl::invoke (std::shared_ptr<MediaObjectImpl> obj, const std::string &methodName, const Json::Value &params, Json::Value &response)
{
  if (methodName == "setSource") {
    kurento::JsonSerializer s (false);
    DispatcherOneToManyMethodSetSource method;

    s.JsonValue = params;
    method.Serialize (s);

    method.invoke (std::dynamic_pointer_cast<DispatcherOneToMany> (obj) );
    return;
  }

  if (methodName == "removeSource") {
    kurento::JsonSerializer s (false);
    DispatcherOneToManyMethodRemoveSource method;

    s.JsonValue = params;
    method.Serialize (s);

    method.invoke (std::dynamic_pointer_cast<DispatcherOneToMany> (obj) );
    return;
  }

  HubImpl::invoke (obj, methodName, params, response);
}

bool
DispatcherOneToManyImpl::connect (const std::string &eventType, std::shared_ptr<EventHandler> handler)
{

  return HubImpl::connect (eventType, handler);
}

void
DispatcherOneToManyImpl::Serialize (JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    try {
      Json::Value v (getId() );

      serializer.JsonValue = v;
    } catch (std::bad_cast &e) {
    }
  } else {
    throw KurentoException (MARSHALL_ERROR,
                            "'DispatcherOneToManyImpl' cannot be deserialized as an object");
  }
}
} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::DispatcherOneToManyImpl> &object, JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    if (object) {
      object->Serialize (serializer);
    }
  } else {
    std::shared_ptr<kurento::MediaObjectImpl> aux;
    aux = kurento::DispatcherOneToManyImplFactory::getObject (JsonFixes::getString(serializer.JsonValue) );
    object = std::dynamic_pointer_cast<kurento::DispatcherOneToManyImpl> (aux);
  }
}

void
Serialize (std::shared_ptr<kurento::DispatcherOneToMany> &object, JsonSerializer &serializer)
{
  std::shared_ptr<kurento::DispatcherOneToManyImpl> aux = std::dynamic_pointer_cast<kurento::DispatcherOneToManyImpl> (object);

  Serialize (aux, serializer);
  object = std::dynamic_pointer_cast <kurento::DispatcherOneToMany> (aux);
}

} /* kurento */