/* Autogenerated with kurento-module-creator */

#ifndef __HTTP_ENDPOINT_IMPL_FACTORY_HPP__
#define __HTTP_ENDPOINT_IMPL_FACTORY_HPP__

#include "HttpEndpointImpl.hpp"
#include "SessionEndpointImplFactory.hpp"
#include <Factory.hpp>
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{

class HttpEndpointImplFactory : public virtual SessionEndpointImplFactory
{
public:
  HttpEndpointImplFactory() = default;

  std::string getName() const override {
    return "HttpEndpoint";
  };

};

} /* kurento */

#endif /*  __HTTP_ENDPOINT_IMPL_FACTORY_HPP__ */
