/* Autogenerated with kurento-module-creator */

#ifndef __MIXER_IMPL_FACTORY_HPP__
#define __MIXER_IMPL_FACTORY_HPP__

#include "MixerImpl.hpp"
#include "HubImplFactory.hpp"
#include <Factory.hpp>
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{

class MixerImplFactory : public virtual HubImplFactory
{
public:
  MixerImplFactory() = default;

  std::string getName() const override {
    return "Mixer";
  };

private:

  MediaObjectImpl *createObjectPointer (
      const boost::property_tree::ptree &conf,
      const Json::Value &params) const override;

  MediaObjectImpl *createObject (const boost::property_tree::ptree &conf, std::shared_ptr<MediaPipeline> mediaPipeline) const;
};

} /* kurento */

#endif /*  __MIXER_IMPL_FACTORY_HPP__ */
