/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include "VideoInfo.hpp"
#include "PlayerEndpointImpl.hpp"
#include "PlayerEndpointImplFactory.hpp"
#include "PlayerEndpointInternal.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

using kurento::KurentoException;

namespace kurento
{

MediaObjectImpl *PlayerEndpointImplFactory::createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const
{
  kurento::JsonSerializer s (false);
  PlayerEndpointConstructor constructor;

  s.JsonValue = params;
  constructor.Serialize (s);

  return createObject (conf, constructor.getMediaPipeline(), constructor.getUri(), constructor.getUseEncodedMedia(), constructor.getNetworkCache() );
}

void
PlayerEndpointImpl::invoke (std::shared_ptr<MediaObjectImpl> obj, const std::string &methodName, const Json::Value &params, Json::Value &response)
{
  if (methodName == "play") {
    kurento::JsonSerializer s (false);
    PlayerEndpointMethodPlay method;

    s.JsonValue = params;
    method.Serialize (s);

    method.invoke (std::dynamic_pointer_cast<PlayerEndpoint> (obj) );
    return;
  }

  if (methodName == "getVideoInfo") {
    std::shared_ptr<VideoInfo> ret;
    JsonSerializer responseSerializer (true);

    ret = std::dynamic_pointer_cast<PlayerEndpoint> (obj)->getVideoInfo ();
    responseSerializer.SerializeNVP (ret);
    response = responseSerializer.JsonValue["ret"];
    return;
  }

  if (methodName == "getElementGstreamerDot") {
    std::string ret;
    JsonSerializer responseSerializer (true);

    ret = std::dynamic_pointer_cast<PlayerEndpoint> (obj)->getElementGstreamerDot ();
    responseSerializer.SerializeNVP (ret);
    response = responseSerializer.JsonValue["ret"];
    return;
  }

  if (methodName == "getPosition") {
    int64_t ret;
    JsonSerializer responseSerializer (true);

    ret = std::dynamic_pointer_cast<PlayerEndpoint> (obj)->getPosition ();
    responseSerializer.SerializeNVP (ret);
    response = responseSerializer.JsonValue["ret"];
    return;
  }

  if (methodName == "setPosition") {
    kurento::JsonSerializer s (false);
    int64_t position;
    s.JsonValue = params;

    if (!s.JsonValue.isMember ("position") || !s.JsonValue["position"].isConvertibleTo (Json::ValueType::int64Value) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'position' parameter should be a int64");
    }

    if (!s.IsWriter) {
      s.SerializeNVP (position);
      std::dynamic_pointer_cast<PlayerEndpoint> (obj)->setPosition (position);
    }
    return;
  }

  UriEndpointImpl::invoke (obj, methodName, params, response);
}

bool
PlayerEndpointImpl::connect (const std::string &eventType, std::shared_ptr<EventHandler> handler)
{

  if ("EndOfStream" == eventType) {
    std::weak_ptr<EventHandler> wh = handler;

    sigc::connection conn = signalEndOfStream.connect ([ &, wh] (EndOfStream event) {
      std::shared_ptr<EventHandler> lh = wh.lock();
      if (!lh)
        return;

      std::shared_ptr<EndOfStream> ev_ref (new EndOfStream(event));
      auto object = this->shared_from_this();

      lh->sendEventAsync ([ev_ref, object, lh] {
        JsonSerializer s (true);

        s.Serialize ("data", ev_ref.get());
        s.Serialize ("object", object.get());
        s.JsonValue["type"] = "EndOfStream";

        lh->sendEvent (s.JsonValue);
      });
    });
    handler->setConnection (conn);
    return true;
  }

  return UriEndpointImpl::connect (eventType, handler);
}

void
PlayerEndpointImpl::Serialize (JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    try {
      Json::Value v (getId() );

      serializer.JsonValue = v;
    } catch (std::bad_cast &e) {
    }
  } else {
    throw KurentoException (MARSHALL_ERROR,
                            "'PlayerEndpointImpl' cannot be deserialized as an object");
  }
}
} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::PlayerEndpointImpl> &object, JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    if (object) {
      object->Serialize (serializer);
    }
  } else {
    std::shared_ptr<kurento::MediaObjectImpl> aux;
    aux = kurento::PlayerEndpointImplFactory::getObject (JsonFixes::getString(serializer.JsonValue) );
    object = std::dynamic_pointer_cast<kurento::PlayerEndpointImpl> (aux);
  }
}

void
Serialize (std::shared_ptr<kurento::PlayerEndpoint> &object, JsonSerializer &serializer)
{
  std::shared_ptr<kurento::PlayerEndpointImpl> aux = std::dynamic_pointer_cast<kurento::PlayerEndpointImpl> (object);

  Serialize (aux, serializer);
  object = std::dynamic_pointer_cast <kurento::PlayerEndpoint> (aux);
}

} /* kurento */