/* Autogenerated with kurento-module-creator */

#ifndef __PLAYER_ENDPOINT_IMPL_FACTORY_HPP__
#define __PLAYER_ENDPOINT_IMPL_FACTORY_HPP__

#include "PlayerEndpointImpl.hpp"
#include "UriEndpointImplFactory.hpp"
#include <Factory.hpp>
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{

class PlayerEndpointImplFactory : public virtual UriEndpointImplFactory
{
public:
  PlayerEndpointImplFactory() = default;

  std::string getName() const override {
    return "PlayerEndpoint";
  };

private:

  MediaObjectImpl *createObjectPointer (
      const boost::property_tree::ptree &conf,
      const Json::Value &params) const override;

  MediaObjectImpl *createObject (const boost::property_tree::ptree &conf, std::shared_ptr<MediaPipeline> mediaPipeline, const std::string &uri, bool useEncodedMedia, int networkCache) const;
};

} /* kurento */

#endif /*  __PLAYER_ENDPOINT_IMPL_FACTORY_HPP__ */
