/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include "SDES.hpp"
#include "RtpEndpointImpl.hpp"
#include "RtpEndpointImplFactory.hpp"
#include "RtpEndpointInternal.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

using kurento::KurentoException;

namespace kurento
{

MediaObjectImpl *RtpEndpointImplFactory::createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const
{
  kurento::JsonSerializer s (false);
  RtpEndpointConstructor constructor;

  s.JsonValue = params;
  constructor.Serialize (s);

  return createObject (conf, constructor.getMediaPipeline(), constructor.getCrypto(), constructor.getUseIpv6() );
}

void
RtpEndpointImpl::invoke (std::shared_ptr<MediaObjectImpl> obj, const std::string &methodName, const Json::Value &params, Json::Value &response)
{
  BaseRtpEndpointImpl::invoke (obj, methodName, params, response);
}

bool
RtpEndpointImpl::connect (const std::string &eventType, std::shared_ptr<EventHandler> handler)
{

  if ("OnKeySoftLimit" == eventType) {
    std::weak_ptr<EventHandler> wh = handler;

    sigc::connection conn = signalOnKeySoftLimit.connect ([ &, wh] (OnKeySoftLimit event) {
      std::shared_ptr<EventHandler> lh = wh.lock();
      if (!lh)
        return;

      std::shared_ptr<OnKeySoftLimit> ev_ref (new OnKeySoftLimit(event));
      auto object = this->shared_from_this();

      lh->sendEventAsync ([ev_ref, object, lh] {
        JsonSerializer s (true);

        s.Serialize ("data", ev_ref.get());
        s.Serialize ("object", object.get());
        s.JsonValue["type"] = "OnKeySoftLimit";

        lh->sendEvent (s.JsonValue);
      });
    });
    handler->setConnection (conn);
    return true;
  }

  return BaseRtpEndpointImpl::connect (eventType, handler);
}

void
RtpEndpointImpl::Serialize (JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    try {
      Json::Value v (getId() );

      serializer.JsonValue = v;
    } catch (std::bad_cast &e) {
    }
  } else {
    throw KurentoException (MARSHALL_ERROR,
                            "'RtpEndpointImpl' cannot be deserialized as an object");
  }
}
} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::RtpEndpointImpl> &object, JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    if (object) {
      object->Serialize (serializer);
    }
  } else {
    std::shared_ptr<kurento::MediaObjectImpl> aux;
    aux = kurento::RtpEndpointImplFactory::getObject (JsonFixes::getString(serializer.JsonValue) );
    object = std::dynamic_pointer_cast<kurento::RtpEndpointImpl> (aux);
  }
}

void
Serialize (std::shared_ptr<kurento::RtpEndpoint> &object, JsonSerializer &serializer)
{
  std::shared_ptr<kurento::RtpEndpointImpl> aux = std::dynamic_pointer_cast<kurento::RtpEndpointImpl> (object);

  Serialize (aux, serializer);
  object = std::dynamic_pointer_cast <kurento::RtpEndpoint> (aux);
}

} /* kurento */