/* Autogenerated with kurento-module-creator */

#ifndef __WEB_RTC_ENDPOINT_IMPL_FACTORY_HPP__
#define __WEB_RTC_ENDPOINT_IMPL_FACTORY_HPP__

#include "WebRtcEndpointImpl.hpp"
#include "BaseRtpEndpointImplFactory.hpp"
#include <Factory.hpp>
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{

class WebRtcEndpointImplFactory : public virtual BaseRtpEndpointImplFactory
{
public:
  WebRtcEndpointImplFactory() = default;

  std::string getName() const override {
    return "WebRtcEndpoint";
  };

private:

  MediaObjectImpl *createObjectPointer (
      const boost::property_tree::ptree &conf,
      const Json::Value &params) const override;

  MediaObjectImpl *createObject (const boost::property_tree::ptree &conf, std::shared_ptr<MediaPipeline> mediaPipeline, bool recvonly, bool sendonly, bool useDataChannels, std::shared_ptr<CertificateKeyType> certificateKeyType) const;
};

} /* kurento */

#endif /*  __WEB_RTC_ENDPOINT_IMPL_FACTORY_HPP__ */
