/* Autogenerated with kurento-module-creator */

#include "FaceOverlayFilter.hpp"
#include <mutex>

namespace kurento
{

static std::vector<std::string> hierarchyFaceOverlayFilter;
std::once_flag initFlagFaceOverlayFilter;

static void
initHierarchy ()
{
  hierarchyFaceOverlayFilter.emplace_back("kurento.Filter");
  hierarchyFaceOverlayFilter.emplace_back("kurento.MediaElement");
  hierarchyFaceOverlayFilter.emplace_back("kurento.MediaObject");
}

const std::vector<std::string> &
FaceOverlayFilter::getHierarchy () const
{
  std::call_once (initFlagFaceOverlayFilter,initHierarchy);
  return hierarchyFaceOverlayFilter;
}

const std::string&
FaceOverlayFilter::getType () const {
  static std::string typeName = "FaceOverlayFilter";

  return typeName;
}

const std::string&
FaceOverlayFilter::getQualifiedType () const {
  static std::string qualifiedTypeName = getModule() + "." + getType();

  return qualifiedTypeName;
}

const std::string&
FaceOverlayFilter::getModule () const {
  static std::string moduleName =  "kurento";

  return moduleName;
}

} /* kurento */
