/* Autogenerated with kurento-module-creator */

#include "GStreamerFilter.hpp"
#include <mutex>

namespace kurento
{

static std::vector<std::string> hierarchyGStreamerFilter;
std::once_flag initFlagGStreamerFilter;

static void
initHierarchy ()
{
  hierarchyGStreamerFilter.emplace_back("kurento.Filter");
  hierarchyGStreamerFilter.emplace_back("kurento.MediaElement");
  hierarchyGStreamerFilter.emplace_back("kurento.MediaObject");
}

const std::vector<std::string> &
GStreamerFilter::getHierarchy () const
{
  std::call_once (initFlagGStreamerFilter,initHierarchy);
  return hierarchyGStreamerFilter;
}

const std::string&
GStreamerFilter::getType () const {
  static std::string typeName = "GStreamerFilter";

  return typeName;
}

const std::string&
GStreamerFilter::getQualifiedType () const {
  static std::string qualifiedTypeName = getModule() + "." + getType();

  return qualifiedTypeName;
}

const std::string&
GStreamerFilter::getModule () const {
  static std::string moduleName =  "kurento";

  return moduleName;
}

} /* kurento */
