/* Autogenerated with kurento-module-creator */

#ifndef __GSTREAMER_FILTER_HPP__
#define __GSTREAMER_FILTER_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "Filter.hpp"

namespace kurento
{
class GStreamerFilter;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::GStreamerFilter> &object, JsonSerializer &serializer);
}

namespace kurento
{
class MediaPipeline;
class FilterType;
} /* kurento */

namespace kurento
{
class GStreamerFilter : public virtual Filter
{

public:
  GStreamerFilter() = default;
  ~GStreamerFilter() override = default;


  virtual void setElementProperty (const std::string &propertyName, const std::string &propertyValue) = 0;

  const std::string &getType() const override;
  const std::string &getQualifiedType() const override;
  const std::string &getModule() const override;
  const std::vector<std::string> &getHierarchy() const override;

  void Serialize(JsonSerializer &serializer) override = 0;

  virtual std::string getCommand () = 0;

};

} /* kurento */

#endif /*  __GSTREAMER_FILTER_HPP__ */
