/* Autogenerated with kurento-module-creator */

#include "ImageOverlayFilter.hpp"
#include <mutex>

namespace kurento
{

static std::vector<std::string> hierarchyImageOverlayFilter;
std::once_flag initFlagImageOverlayFilter;

static void
initHierarchy ()
{
  hierarchyImageOverlayFilter.emplace_back("kurento.Filter");
  hierarchyImageOverlayFilter.emplace_back("kurento.MediaElement");
  hierarchyImageOverlayFilter.emplace_back("kurento.MediaObject");
}

const std::vector<std::string> &
ImageOverlayFilter::getHierarchy () const
{
  std::call_once (initFlagImageOverlayFilter,initHierarchy);
  return hierarchyImageOverlayFilter;
}

const std::string&
ImageOverlayFilter::getType () const {
  static std::string typeName = "ImageOverlayFilter";

  return typeName;
}

const std::string&
ImageOverlayFilter::getQualifiedType () const {
  static std::string qualifiedTypeName = getModule() + "." + getType();

  return qualifiedTypeName;
}

const std::string&
ImageOverlayFilter::getModule () const {
  static std::string moduleName =  "kurento";

  return moduleName;
}

} /* kurento */
