/* Autogenerated with kurento-module-creator */

#ifndef __OPEN_CVFILTER_INTERNAL_HPP__
#define __OPEN_CVFILTER_INTERNAL_HPP__

#include "OpenCVFilter.hpp"

namespace kurento
{
class JsonSerializer;
}

namespace kurento
{

} /* kurento */

#endif /*  __OPEN_CVFILTER_INTERNAL_HPP__ */
