/* Autogenerated with kurento-module-creator */

#include "OpenCVFilter.hpp"
#include <mutex>

namespace kurento
{

static std::vector<std::string> hierarchyOpenCVFilter;
std::once_flag initFlagOpenCVFilter;

static void
initHierarchy ()
{
  hierarchyOpenCVFilter.emplace_back("kurento.Filter");
  hierarchyOpenCVFilter.emplace_back("kurento.MediaElement");
  hierarchyOpenCVFilter.emplace_back("kurento.MediaObject");
}

const std::vector<std::string> &
OpenCVFilter::getHierarchy () const
{
  std::call_once (initFlagOpenCVFilter,initHierarchy);
  return hierarchyOpenCVFilter;
}

const std::string&
OpenCVFilter::getType () const {
  static std::string typeName = "OpenCVFilter";

  return typeName;
}

const std::string&
OpenCVFilter::getQualifiedType () const {
  static std::string qualifiedTypeName = getModule() + "." + getType();

  return qualifiedTypeName;
}

const std::string&
OpenCVFilter::getModule () const {
  static std::string moduleName =  "kurento";

  return moduleName;
}

} /* kurento */
