/* Autogenerated with kurento-module-creator */

#ifndef __ZBAR_FILTER_HPP__
#define __ZBAR_FILTER_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "Filter.hpp"
#include "CodeFound.hpp"
#include <sigc++/sigc++.h>

namespace kurento
{
class ZBarFilter;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::ZBarFilter> &object, JsonSerializer &serializer);
}

namespace kurento
{
class MediaPipeline;
} /* kurento */

namespace kurento
{
class ZBarFilter : public virtual Filter
{

public:
  ZBarFilter() = default;
  ~ZBarFilter() override = default;


  const std::string &getType() const override;
  const std::string &getQualifiedType() const override;
  const std::string &getModule() const override;
  const std::vector<std::string> &getHierarchy() const override;

  void Serialize(JsonSerializer &serializer) override = 0;

};

} /* kurento */

#endif /*  __ZBAR_FILTER_HPP__ */
