/* Autogenerated with kurento-module-creator */

#ifndef __AUDIO_CODEC_HPP__
#define __AUDIO_CODEC_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>


namespace kurento
{
class AudioCodec;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::AudioCodec> &object, JsonSerializer &s);
} /* kurento */

namespace kurento
{

class AudioCodec
{

public:

  typedef enum {
    OPUS,
    PCMU,
    RAW
  } type;

  AudioCodec (const std::string &value) {
    enumValue = getValueFromString (value);
  };

  AudioCodec (type value) {
    this->enumValue = value;
  }

  type getValue () {
    return enumValue;
  };

  std::string getString () {

    if (enumValue ==  OPUS) {
      return "OPUS";
    }

    if (enumValue ==  PCMU) {
      return "PCMU";
    }

    if (enumValue ==  RAW) {
      return "RAW";
    }

    return "";
  }

  void Serialize (JsonSerializer &s);

  AudioCodec() = default;

private:

  static type getValueFromString (const std::string &value);

  type enumValue;

  friend void kurento::Serialize (std::shared_ptr<kurento::AudioCodec> &object, JsonSerializer &s);

};

} /* kurento */

#endif /*  __AUDIO_CODEC_HPP__ */
