/* Autogenerated with kurento-module-creator */

#include "AudioCodec.hpp"
#include "AudioCaps.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

namespace kurento
{

void AudioCaps::Serialize (JsonSerializer &s)
{

  if (s.IsWriter) {
    s.JsonValue["__type__"] = "AudioCaps";
    s.JsonValue["__module__"] = "kurento";

    s.SerializeNVP (codec);

    s.SerializeNVP (bitrate);

  } else {
    if (!s.JsonValue.isMember ("codec") || !s.JsonValue["codec"].isConvertibleTo (Json::ValueType::stringValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'codec' property should be a string");
    }

    s.SerializeNVP (codec);

    if (!s.JsonValue.isMember ("bitrate") || !s.JsonValue["bitrate"].isConvertibleTo (Json::ValueType::intValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'bitrate' property should be a integer");
    }

    s.SerializeNVP (bitrate);

  }
}

} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::AudioCaps> &object, JsonSerializer &s)
{
  if (!s.IsWriter && !object) {
    if (!s.JsonValue.isMember ("__type__") || !s.JsonValue["__type__"].isConvertibleTo (Json::ValueType::stringValue) || !s.JsonValue.isMember ("__module__") || !s.JsonValue["__module__"].isConvertibleTo (Json::ValueType::stringValue)) {
      object.reset (new kurento::AudioCaps() );
    } else {
      auto ptr = kurento::RegisterParent::createRegister (s.JsonValue["__module__"].asString () + "." + s.JsonValue["__type__"].asString ());

      if (!ptr) {
        throw KurentoException (UNEXPECTED_ERROR,
                                "Type " + s.JsonValue["__type__"].asString () + " does not exist in module " + s.JsonValue["__module__"].asString ());
      }

      object.reset (dynamic_cast <kurento::AudioCaps*> (ptr));

      if (!object) {
        delete ptr;
        throw KurentoException (UNEXPECTED_ERROR, "Type " + s.JsonValue["__type__"].asString () + " is not compatible");
      }
    }
  }

  if (object) {
    object->Serialize (s);
  }
}

} /* kurento */