/* Autogenerated with kurento-module-creator */

#include <iostream>
#include "BaseRtpEndpointInternal.hpp"
#include <KurentoException.hpp>
#include <jsonrpc/JsonSerializer.hpp>
#include "MediaState.hpp"
#include "ConnectionState.hpp"
#include "RembParams.hpp"

namespace kurento
{

} /* kurento */
