/* Autogenerated with kurento-module-creator */

#include "BaseRtpEndpoint.hpp"
#include <mutex>

namespace kurento
{

static std::vector<std::string> hierarchyBaseRtpEndpoint;
std::once_flag initFlagBaseRtpEndpoint;

static void
initHierarchy ()
{
  hierarchyBaseRtpEndpoint.emplace_back("kurento.SdpEndpoint");
  hierarchyBaseRtpEndpoint.emplace_back("kurento.SessionEndpoint");
  hierarchyBaseRtpEndpoint.emplace_back("kurento.Endpoint");
  hierarchyBaseRtpEndpoint.emplace_back("kurento.MediaElement");
  hierarchyBaseRtpEndpoint.emplace_back("kurento.MediaObject");
}

const std::vector<std::string> &
BaseRtpEndpoint::getHierarchy () const
{
  std::call_once (initFlagBaseRtpEndpoint,initHierarchy);
  return hierarchyBaseRtpEndpoint;
}

const std::string&
BaseRtpEndpoint::getType () const {
  static std::string typeName = "BaseRtpEndpoint";

  return typeName;
}

const std::string&
BaseRtpEndpoint::getQualifiedType () const {
  static std::string qualifiedTypeName = getModule() + "." + getType();

  return qualifiedTypeName;
}

const std::string&
BaseRtpEndpoint::getModule () const {
  static std::string moduleName =  "kurento";

  return moduleName;
}

} /* kurento */
