/* Autogenerated with kurento-module-creator */

#include "ConnectionState.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

namespace kurento
{

ConnectionState::type ConnectionState::getValueFromString (const std::string &value)
{

  if (value ==  "DISCONNECTED") {
    return DISCONNECTED;
  }

  if (value ==  "CONNECTED") {
    return CONNECTED;
  }

  throw KurentoException (MARSHALL_ERROR,
                          "Invalid value for 'ConnectionState'");

}

void ConnectionState::Serialize (JsonSerializer &s)
{
  if (s.IsWriter) {
    s.JsonValue = getString();
  } else {
    if (s.JsonValue.isConvertibleTo (Json::ValueType::stringValue) ) {
      enumValue = getValueFromString (s.JsonValue.asString() );
    } else {
      throw KurentoException (MARSHALL_ERROR,
                              "'ConnectionState' type should be a string");
    }
  }
}

} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::ConnectionState> &object, JsonSerializer &s)
{
  if (!s.IsWriter && !object) {
    object.reset (new kurento::ConnectionState() );
  }

  if (object) {
    object->Serialize (s);
  }
}

} /* kurento */