/* Autogenerated with kurento-module-creator */

#include "MediaLatencyStat.hpp"
#include "ElementStats.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

namespace kurento
{

void ElementStats::Serialize (JsonSerializer &s)
{
  Stats::Serialize (s);


  if (s.IsWriter) {
    s.JsonValue["__type__"] = "ElementStats";
    s.JsonValue["__module__"] = "kurento";

    s.SerializeNVP (inputAudioLatency);

    s.SerializeNVP (inputVideoLatency);

    s.SerializeNVP (inputLatency);

  } else {
    if (!s.JsonValue.isMember ("inputAudioLatency") || !s.JsonValue["inputAudioLatency"].isConvertibleTo (Json::ValueType::realValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'inputAudioLatency' property should be a double");
    }

    s.SerializeNVP (inputAudioLatency);

    if (!s.JsonValue.isMember ("inputVideoLatency") || !s.JsonValue["inputVideoLatency"].isConvertibleTo (Json::ValueType::realValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'inputVideoLatency' property should be a double");
    }

    s.SerializeNVP (inputVideoLatency);

    if (!s.JsonValue.isMember ("inputLatency") || !s.JsonValue["inputLatency"].isConvertibleTo (Json::ValueType::arrayValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'inputLatency' property should be a list");
    }

    s.SerializeNVP (inputLatency);

  }
}

} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::ElementStats> &object, JsonSerializer &s)
{
  if (!s.IsWriter && !object) {
    if (!s.JsonValue.isMember ("__type__") || !s.JsonValue["__type__"].isConvertibleTo (Json::ValueType::stringValue) || !s.JsonValue.isMember ("__module__") || !s.JsonValue["__module__"].isConvertibleTo (Json::ValueType::stringValue)) {
      object.reset (new kurento::ElementStats() );
    } else {
      auto ptr = kurento::RegisterParent::createRegister (s.JsonValue["__module__"].asString () + "." + s.JsonValue["__type__"].asString ());

      if (!ptr) {
        throw KurentoException (UNEXPECTED_ERROR,
                                "Type " + s.JsonValue["__type__"].asString () + " does not exist in module " + s.JsonValue["__module__"].asString ());
      }

      object.reset (dynamic_cast <kurento::ElementStats*> (ptr));

      if (!object) {
        delete ptr;
        throw KurentoException (UNEXPECTED_ERROR, "Type " + s.JsonValue["__type__"].asString () + " is not compatible");
      }
    }
  }

  if (object) {
    object->Serialize (s);
  }
}

} /* kurento */