/* Autogenerated with kurento-module-creator */

#include "ElementDisconnected.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include "MediaElement.hpp"
#include "MediaType.hpp"
#include <chrono>
#include <ctime>
#include <string>

namespace kurento
{

void
ElementDisconnected::Serialize (JsonSerializer &s)
{
  Media::Serialize (s);

  s.SerializeNVP (sink);
  s.SerializeNVP (mediaType);
  s.SerializeNVP (sourceMediaDescription);
  s.SerializeNVP (sinkMediaDescription);
}

} /* kurento */

namespace kurento
{

void Serialize (std::shared_ptr<kurento::ElementDisconnected> &event, JsonSerializer &s)
{
  if (!s.IsWriter && !event) {
    event.reset (new kurento::ElementDisconnected() );
  }

  if (event) {
    event->Serialize (s);
  }
}

} /* kurento */
