/* Autogenerated with kurento-module-creator */

#ifndef __ENDPOINT_HPP__
#define __ENDPOINT_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "MediaElement.hpp"

namespace kurento
{
class Endpoint;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::Endpoint> &object, JsonSerializer &serializer);
}

namespace kurento
{
class Endpoint : public virtual MediaElement
{

public:
  Endpoint() = default;
  ~Endpoint() override = default;


  const std::string &getType() const override;
  const std::string &getQualifiedType() const override;
  const std::string &getModule() const override;
  const std::vector<std::string> &getHierarchy() const override;

  void Serialize(JsonSerializer &serializer) override = 0;

};

} /* kurento */

#endif /*  __ENDPOINT_HPP__ */
