/* Autogenerated with kurento-module-creator */

#include "MediaLatencyStat.hpp"
#include "EndpointStats.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

namespace kurento
{

void EndpointStats::Serialize (JsonSerializer &s)
{
  ElementStats::Serialize (s);


  if (s.IsWriter) {
    s.JsonValue["__type__"] = "EndpointStats";
    s.JsonValue["__module__"] = "kurento";

    s.SerializeNVP (audioE2ELatency);

    s.SerializeNVP (videoE2ELatency);

    s.SerializeNVP (E2ELatency);

  } else {
    if (!s.JsonValue.isMember ("audioE2ELatency") || !s.JsonValue["audioE2ELatency"].isConvertibleTo (Json::ValueType::realValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'audioE2ELatency' property should be a double");
    }

    s.SerializeNVP (audioE2ELatency);

    if (!s.JsonValue.isMember ("videoE2ELatency") || !s.JsonValue["videoE2ELatency"].isConvertibleTo (Json::ValueType::realValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'videoE2ELatency' property should be a double");
    }

    s.SerializeNVP (videoE2ELatency);

    if (!s.JsonValue.isMember ("E2ELatency") || !s.JsonValue["E2ELatency"].isConvertibleTo (Json::ValueType::arrayValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'E2ELatency' property should be a list");
    }

    s.SerializeNVP (E2ELatency);

  }
}

} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::EndpointStats> &object, JsonSerializer &s)
{
  if (!s.IsWriter && !object) {
    if (!s.JsonValue.isMember ("__type__") || !s.JsonValue["__type__"].isConvertibleTo (Json::ValueType::stringValue) || !s.JsonValue.isMember ("__module__") || !s.JsonValue["__module__"].isConvertibleTo (Json::ValueType::stringValue)) {
      object.reset (new kurento::EndpointStats() );
    } else {
      auto ptr = kurento::RegisterParent::createRegister (s.JsonValue["__module__"].asString () + "." + s.JsonValue["__type__"].asString ());

      if (!ptr) {
        throw KurentoException (UNEXPECTED_ERROR,
                                "Type " + s.JsonValue["__type__"].asString () + " does not exist in module " + s.JsonValue["__module__"].asString ());
      }

      object.reset (dynamic_cast <kurento::EndpointStats*> (ptr));

      if (!object) {
        delete ptr;
        throw KurentoException (UNEXPECTED_ERROR, "Type " + s.JsonValue["__type__"].asString () + " is not compatible");
      }
    }
  }

  if (object) {
    object->Serialize (s);
  }
}

} /* kurento */