/* Autogenerated with kurento-module-creator */

#include "Error.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <chrono>
#include <ctime>
#include <string>

namespace kurento
{

void
Error::Serialize (JsonSerializer &s)
{
  RaiseBase::Serialize (s);

  s.SerializeNVP (description);
  s.SerializeNVP (errorCode);
  s.SerializeNVP (type);
}

} /* kurento */

namespace kurento
{

void Serialize (std::shared_ptr<kurento::Error> &event, JsonSerializer &s)
{
  if (!s.IsWriter && !event) {
    event.reset (new kurento::Error() );
  }

  if (event) {
    event->Serialize (s);
  }
}

} /* kurento */
