/* Autogenerated with kurento-module-creator */

#include <iostream>
#include "FilterInternal.hpp"
#include <KurentoException.hpp>
#include <jsonrpc/JsonSerializer.hpp>

namespace kurento
{

} /* kurento */
