/* Autogenerated with kurento-module-creator */

#include "Filter.hpp"
#include <mutex>

namespace kurento
{

static std::vector<std::string> hierarchyFilter;
std::once_flag initFlagFilter;

static void
initHierarchy ()
{
  hierarchyFilter.emplace_back("kurento.MediaElement");
  hierarchyFilter.emplace_back("kurento.MediaObject");
}

const std::vector<std::string> &
Filter::getHierarchy () const
{
  std::call_once (initFlagFilter,initHierarchy);
  return hierarchyFilter;
}

const std::string&
Filter::getType () const {
  static std::string typeName = "Filter";

  return typeName;
}

const std::string&
Filter::getQualifiedType () const {
  static std::string qualifiedTypeName = getModule() + "." + getType();

  return qualifiedTypeName;
}

const std::string&
Filter::getModule () const {
  static std::string moduleName =  "kurento";

  return moduleName;
}

} /* kurento */
