/* Autogenerated with kurento-module-creator */

#include "FilterType.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

namespace kurento
{

FilterType::type FilterType::getValueFromString (const std::string &value)
{

  if (value ==  "AUDIO") {
    return AUDIO;
  }

  if (value ==  "AUTODETECT") {
    return AUTODETECT;
  }

  if (value ==  "VIDEO") {
    return VIDEO;
  }

  throw KurentoException (MARSHALL_ERROR,
                          "Invalid value for 'FilterType'");

}

void FilterType::Serialize (JsonSerializer &s)
{
  if (s.IsWriter) {
    s.JsonValue = getString();
  } else {
    if (s.JsonValue.isConvertibleTo (Json::ValueType::stringValue) ) {
      enumValue = getValueFromString (s.JsonValue.asString() );
    } else {
      throw KurentoException (MARSHALL_ERROR,
                              "'FilterType' type should be a string");
    }
  }
}

} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::FilterType> &object, JsonSerializer &s)
{
  if (!s.IsWriter && !object) {
    object.reset (new kurento::FilterType() );
  }

  if (object) {
    object->Serialize (s);
  }
}

} /* kurento */