/* Autogenerated with kurento-module-creator */

#ifndef __FILTER_INTERNAL_HPP__
#define __FILTER_INTERNAL_HPP__

#include "Filter.hpp"

namespace kurento
{
class JsonSerializer;
}

namespace kurento
{

} /* kurento */

#endif /*  __FILTER_INTERNAL_HPP__ */
