/* Autogenerated with kurento-module-creator */

#include "GstreamerDotDetails.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

namespace kurento
{

GstreamerDotDetails::type GstreamerDotDetails::getValueFromString (const std::string &value)
{

  if (value ==  "SHOW_MEDIA_TYPE") {
    return SHOW_MEDIA_TYPE;
  }

  if (value ==  "SHOW_CAPS_DETAILS") {
    return SHOW_CAPS_DETAILS;
  }

  if (value ==  "SHOW_NON_DEFAULT_PARAMS") {
    return SHOW_NON_DEFAULT_PARAMS;
  }

  if (value ==  "SHOW_STATES") {
    return SHOW_STATES;
  }

  if (value ==  "SHOW_FULL_PARAMS") {
    return SHOW_FULL_PARAMS;
  }

  if (value ==  "SHOW_ALL") {
    return SHOW_ALL;
  }

  if (value ==  "SHOW_VERBOSE") {
    return SHOW_VERBOSE;
  }

  throw KurentoException (MARSHALL_ERROR,
                          "Invalid value for 'GstreamerDotDetails'");

}

void GstreamerDotDetails::Serialize (JsonSerializer &s)
{
  if (s.IsWriter) {
    s.JsonValue = getString();
  } else {
    if (s.JsonValue.isConvertibleTo (Json::ValueType::stringValue) ) {
      enumValue = getValueFromString (s.JsonValue.asString() );
    } else {
      throw KurentoException (MARSHALL_ERROR,
                              "'GstreamerDotDetails' type should be a string");
    }
  }
}

} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::GstreamerDotDetails> &object, JsonSerializer &s)
{
  if (!s.IsWriter && !object) {
    object.reset (new kurento::GstreamerDotDetails() );
  }

  if (object) {
    object->Serialize (s);
  }
}

} /* kurento */