/* Autogenerated with kurento-module-creator */

#include "Hub.hpp"
#include <mutex>

namespace kurento
{

static std::vector<std::string> hierarchyHub;
std::once_flag initFlagHub;

static void
initHierarchy ()
{
  hierarchyHub.emplace_back("kurento.MediaObject");
}

const std::vector<std::string> &
Hub::getHierarchy () const
{
  std::call_once (initFlagHub,initHierarchy);
  return hierarchyHub;
}

const std::string&
Hub::getType () const {
  static std::string typeName = "Hub";

  return typeName;
}

const std::string&
Hub::getQualifiedType () const {
  static std::string qualifiedTypeName = getModule() + "." + getType();

  return qualifiedTypeName;
}

const std::string&
Hub::getModule () const {
  static std::string moduleName =  "kurento";

  return moduleName;
}

} /* kurento */
