/* Autogenerated with kurento-module-creator */

#include <iostream>
#include "HubPortInternal.hpp"
#include <KurentoException.hpp>
#include <jsonrpc/JsonSerializer.hpp>
#include "Hub.hpp"

namespace kurento
{

std::shared_ptr<Hub> HubPortConstructor::getHub ()
{
  return hub;
}

void HubPortConstructor::Serialize (kurento::JsonSerializer &s)
{
  if (s.IsWriter) {
    s.SerializeNVP (hub);

  } else {
    if (s.JsonValue.isNull ()) {
      throw KurentoException (MARSHALL_ERROR,
                              "'constructorParams' is required");
    } else if (!s.JsonValue.isObject ()){
      throw KurentoException (MARSHALL_ERROR,
                              "'constructorParams' should be an object");
    }

    if (!s.JsonValue.isMember ("hub") || !s.JsonValue["hub"].isConvertibleTo (Json::ValueType::stringValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'hub' parameter should be a string");
    }

    s.SerializeNVP (hub);

  }
}

} /* kurento */
