/* Autogenerated with kurento-module-creator */

#ifndef __HUB_PORT_INTERNAL_HPP__
#define __HUB_PORT_INTERNAL_HPP__

#include "HubPort.hpp"

namespace kurento
{
class JsonSerializer;
}

namespace kurento
{
class Hub;
} /* kurento */

namespace kurento
{

class HubPortConstructor
{
public:
  HubPortConstructor() = default;
  ~HubPortConstructor() = default;

  void Serialize (JsonSerializer &serializer);

  std::shared_ptr<Hub> getHub ();

  void setHub (std::shared_ptr<Hub> hub) {
    this->hub = hub;
  }

private:
  std::shared_ptr<Hub> hub;
};

} /* kurento */

#endif /*  __HUB_PORT_INTERNAL_HPP__ */
