/* Autogenerated with kurento-module-creator */

#include "HubPort.hpp"
#include <mutex>

namespace kurento
{

static std::vector<std::string> hierarchyHubPort;
std::once_flag initFlagHubPort;

static void
initHierarchy ()
{
  hierarchyHubPort.emplace_back("kurento.MediaElement");
  hierarchyHubPort.emplace_back("kurento.MediaObject");
}

const std::vector<std::string> &
HubPort::getHierarchy () const
{
  std::call_once (initFlagHubPort,initHierarchy);
  return hierarchyHubPort;
}

const std::string&
HubPort::getType () const {
  static std::string typeName = "HubPort";

  return typeName;
}

const std::string&
HubPort::getQualifiedType () const {
  static std::string qualifiedTypeName = getModule() + "." + getType();

  return qualifiedTypeName;
}

const std::string&
HubPort::getModule () const {
  static std::string moduleName =  "kurento";

  return moduleName;
}

} /* kurento */
