/* Autogenerated with kurento-module-creator */

#include "MediaFlowInStateChange.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include "MediaFlowState.hpp"
#include "MediaType.hpp"
#include <chrono>
#include <ctime>
#include <string>

namespace kurento
{

void
MediaFlowInStateChange::Serialize (JsonSerializer &s)
{
  Media::Serialize (s);

  s.SerializeNVP (state);
  s.SerializeNVP (padName);
  s.SerializeNVP (mediaType);
}

} /* kurento */

namespace kurento
{

void Serialize (std::shared_ptr<kurento::MediaFlowInStateChange> &event, JsonSerializer &s)
{
  if (!s.IsWriter && !event) {
    event.reset (new kurento::MediaFlowInStateChange() );
  }

  if (event) {
    event->Serialize (s);
  }
}

} /* kurento */
