/* Autogenerated with kurento-module-creator */

#include "MediaStateChanged.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include "MediaState.hpp"
#include "MediaState.hpp"
#include <chrono>
#include <ctime>
#include <string>

namespace kurento
{

void
MediaStateChanged::Serialize (JsonSerializer &s)
{
  Media::Serialize (s);

  s.SerializeNVP (oldState);
  s.SerializeNVP (newState);
}

} /* kurento */

namespace kurento
{

void Serialize (std::shared_ptr<kurento::MediaStateChanged> &event, JsonSerializer &s)
{
  if (!s.IsWriter && !event) {
    event.reset (new kurento::MediaStateChanged() );
  }

  if (event) {
    event->Serialize (s);
  }
}

} /* kurento */
