/* Autogenerated with kurento-module-creator */

#include "MediaTranscodingState.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

namespace kurento
{

MediaTranscodingState::type MediaTranscodingState::getValueFromString (const std::string &value)
{

  if (value ==  "TRANSCODING") {
    return TRANSCODING;
  }

  if (value ==  "NOT_TRANSCODING") {
    return NOT_TRANSCODING;
  }

  throw KurentoException (MARSHALL_ERROR,
                          "Invalid value for 'MediaTranscodingState'");

}

void MediaTranscodingState::Serialize (JsonSerializer &s)
{
  if (s.IsWriter) {
    s.JsonValue = getString();
  } else {
    if (s.JsonValue.isConvertibleTo (Json::ValueType::stringValue) ) {
      enumValue = getValueFromString (s.JsonValue.asString() );
    } else {
      throw KurentoException (MARSHALL_ERROR,
                              "'MediaTranscodingState' type should be a string");
    }
  }
}

} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::MediaTranscodingState> &object, JsonSerializer &s)
{
  if (!s.IsWriter && !object) {
    object.reset (new kurento::MediaTranscodingState() );
  }

  if (object) {
    object->Serialize (s);
  }
}

} /* kurento */