/* Autogenerated with kurento-module-creator */

#include "MediaElement.hpp"
#include <mutex>

namespace kurento
{

static std::vector<std::string> hierarchyMediaElement;
std::once_flag initFlagMediaElement;

static void
initHierarchy ()
{
  hierarchyMediaElement.emplace_back("kurento.MediaObject");
}

const std::vector<std::string> &
MediaElement::getHierarchy () const
{
  std::call_once (initFlagMediaElement,initHierarchy);
  return hierarchyMediaElement;
}

const std::string&
MediaElement::getType () const {
  static std::string typeName = "MediaElement";

  return typeName;
}

const std::string&
MediaElement::getQualifiedType () const {
  static std::string qualifiedTypeName = getModule() + "." + getType();

  return qualifiedTypeName;
}

const std::string&
MediaElement::getModule () const {
  static std::string moduleName =  "kurento";

  return moduleName;
}

} /* kurento */
