/* Autogenerated with kurento-module-creator */

#include "MediaType.hpp"
#include "MediaLatencyStat.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

namespace kurento
{

void MediaLatencyStat::Serialize (JsonSerializer &s)
{

  if (s.IsWriter) {
    s.JsonValue["__type__"] = "MediaLatencyStat";
    s.JsonValue["__module__"] = "kurento";

    s.SerializeNVP (name);

    s.SerializeNVP (type);

    s.SerializeNVP (avg);

  } else {
    if (!s.JsonValue.isMember ("name") || !s.JsonValue["name"].isConvertibleTo (Json::ValueType::stringValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'name' property should be a string");
    }

    s.SerializeNVP (name);

    if (!s.JsonValue.isMember ("type") || !s.JsonValue["type"].isConvertibleTo (Json::ValueType::stringValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'type' property should be a string");
    }

    s.SerializeNVP (type);

    if (!s.JsonValue.isMember ("avg") || !s.JsonValue["avg"].isConvertibleTo (Json::ValueType::realValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'avg' property should be a double");
    }

    s.SerializeNVP (avg);

  }
}

} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::MediaLatencyStat> &object, JsonSerializer &s)
{
  if (!s.IsWriter && !object) {
    if (!s.JsonValue.isMember ("__type__") || !s.JsonValue["__type__"].isConvertibleTo (Json::ValueType::stringValue) || !s.JsonValue.isMember ("__module__") || !s.JsonValue["__module__"].isConvertibleTo (Json::ValueType::stringValue)) {
      object.reset (new kurento::MediaLatencyStat() );
    } else {
      auto ptr = kurento::RegisterParent::createRegister (s.JsonValue["__module__"].asString () + "." + s.JsonValue["__type__"].asString ());

      if (!ptr) {
        throw KurentoException (UNEXPECTED_ERROR,
                                "Type " + s.JsonValue["__type__"].asString () + " does not exist in module " + s.JsonValue["__module__"].asString ());
      }

      object.reset (dynamic_cast <kurento::MediaLatencyStat*> (ptr));

      if (!object) {
        delete ptr;
        throw KurentoException (UNEXPECTED_ERROR, "Type " + s.JsonValue["__type__"].asString () + " is not compatible");
      }
    }
  }

  if (object) {
    object->Serialize (s);
  }
}

} /* kurento */