/* Autogenerated with kurento-module-creator */

#ifndef __MEDIA_SESSION_TERMINATED_HPP__
#define __MEDIA_SESSION_TERMINATED_HPP__

#include <json/json.h>
#include <memory>
#include "Media.hpp"

namespace kurento
{
class MediaSessionTerminated;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::MediaSessionTerminated> &object, JsonSerializer &s);
}


namespace kurento
{

class MediaSessionTerminated : public Media
{

public:

  MediaSessionTerminated (std::shared_ptr<MediaObject> source, const std::string &type) : Media (source, type) {
  };

  MediaSessionTerminated (const MediaSessionTerminated &copy) : Media (copy) {
  };

  MediaSessionTerminated (const Json::Value &value);

  static std::string getName() {
    return "MediaSessionTerminated";
  }

  void Serialize (JsonSerializer &s) override;

protected:

  MediaSessionTerminated() = default;

private:

  friend void kurento::Serialize (std::shared_ptr<kurento::MediaSessionTerminated> &event, JsonSerializer &s);
};

} /* kurento */

#endif /*  __MEDIA_SESSION_TERMINATED_HPP__ */
