/* Autogenerated with kurento-module-creator */

#ifndef __MEDIA_OBJECT_INTERNAL_HPP__
#define __MEDIA_OBJECT_INTERNAL_HPP__

#include "MediaObject.hpp"

namespace kurento
{
class JsonSerializer;
}

namespace kurento
{
class Tag;
class MediaPipeline;
class MediaObject;
} /* kurento */

namespace kurento
{

class MediaObjectMethodAddTag
{
public:
  MediaObjectMethodAddTag() = default;
  ~MediaObjectMethodAddTag() = default;

  void invoke (std::shared_ptr<MediaObject> obj);
  void Serialize (JsonSerializer &serializer);

  std::string getKey () {
    return key;
  }

  void setKey (const std::string &key) {
    this->key = key;
  }

  std::string getValue () {
    return value;
  }

  void setValue (const std::string &value) {
    this->value = value;
  }

private:
  std::string key;
  std::string value;
};

class MediaObjectMethodRemoveTag
{
public:
  MediaObjectMethodRemoveTag() = default;
  ~MediaObjectMethodRemoveTag() = default;

  void invoke (std::shared_ptr<MediaObject> obj);
  void Serialize (JsonSerializer &serializer);

  std::string getKey () {
    return key;
  }

  void setKey (const std::string &key) {
    this->key = key;
  }

private:
  std::string key;
};

class MediaObjectMethodGetTag
{
public:
  MediaObjectMethodGetTag() = default;
  ~MediaObjectMethodGetTag() = default;

  std::string invoke (std::shared_ptr<MediaObject> obj);
  void Serialize (JsonSerializer &serializer);

  std::string getKey () {
    return key;
  }

  void setKey (const std::string &key) {
    this->key = key;
  }

private:
  std::string key;
};

class MediaObjectMethodGetTags
{
public:
  MediaObjectMethodGetTags() = default;
  ~MediaObjectMethodGetTags() = default;

  std::vector<std::shared_ptr<Tag>> invoke (std::shared_ptr<MediaObject> obj);
  void Serialize (JsonSerializer &serializer);

};

} /* kurento */

#endif /*  __MEDIA_OBJECT_INTERNAL_HPP__ */
