/* Autogenerated with kurento-module-creator */

#ifndef __MEDIA_STATE_HPP__
#define __MEDIA_STATE_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>


namespace kurento
{
class MediaState;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::MediaState> &object, JsonSerializer &s);
} /* kurento */

namespace kurento
{

class MediaState
{

public:

  typedef enum {
    DISCONNECTED,
    CONNECTED
  } type;

  MediaState (const std::string &value) {
    enumValue = getValueFromString (value);
  };

  MediaState (type value) {
    this->enumValue = value;
  }

  type getValue () {
    return enumValue;
  };

  std::string getString () {

    if (enumValue ==  DISCONNECTED) {
      return "DISCONNECTED";
    }

    if (enumValue ==  CONNECTED) {
      return "CONNECTED";
    }

    return "";
  }

  void Serialize (JsonSerializer &s);

  MediaState() = default;

private:

  static type getValueFromString (const std::string &value);

  type enumValue;

  friend void kurento::Serialize (std::shared_ptr<kurento::MediaState> &object, JsonSerializer &s);

};

} /* kurento */

#endif /*  __MEDIA_STATE_HPP__ */
