/* Autogenerated with kurento-module-creator */

#ifndef __MEDIA_TRANSCODING_STATE_HPP__
#define __MEDIA_TRANSCODING_STATE_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>


namespace kurento
{
class MediaTranscodingState;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::MediaTranscodingState> &object, JsonSerializer &s);
} /* kurento */

namespace kurento
{

class MediaTranscodingState
{

public:

  typedef enum {
    TRANSCODING,
    NOT_TRANSCODING
  } type;

  MediaTranscodingState (const std::string &value) {
    enumValue = getValueFromString (value);
  };

  MediaTranscodingState (type value) {
    this->enumValue = value;
  }

  type getValue () {
    return enumValue;
  };

  std::string getString () {

    if (enumValue ==  TRANSCODING) {
      return "TRANSCODING";
    }

    if (enumValue ==  NOT_TRANSCODING) {
      return "NOT_TRANSCODING";
    }

    return "";
  }

  void Serialize (JsonSerializer &s);

  MediaTranscodingState() = default;

private:

  static type getValueFromString (const std::string &value);

  type enumValue;

  friend void kurento::Serialize (std::shared_ptr<kurento::MediaTranscodingState> &object, JsonSerializer &s);

};

} /* kurento */

#endif /*  __MEDIA_TRANSCODING_STATE_HPP__ */
