/* Autogenerated with kurento-module-creator */

#ifndef __OBJECT_DESTROYED_HPP__
#define __OBJECT_DESTROYED_HPP__

#include <json/json.h>
#include <memory>
#include "RaiseBase.hpp"

namespace kurento
{
class ObjectDestroyed;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::ObjectDestroyed> &object, JsonSerializer &s);
}


namespace kurento
{

class ObjectDestroyed : public RaiseBase
{

public:

  ObjectDestroyed (std::shared_ptr<MediaObject> source, const std::string &objectId) : RaiseBase (source) {
      this->objectId = objectId;
  };

  ObjectDestroyed (const ObjectDestroyed &copy) : RaiseBase (copy) {
      this->objectId = copy.objectId;
  };

  ObjectDestroyed (const Json::Value &value);

  virtual void setObjectId (const std::string &objectId) {
    this->objectId = objectId;
  };

  virtual const std::string &getObjectId () {
    return objectId;
  };

  static std::string getName() {
    return "ObjectDestroyed";
  }

  void Serialize (JsonSerializer &s) override;

protected:

  ObjectDestroyed() = default;

private:
  std::string objectId;

  friend void kurento::Serialize (std::shared_ptr<kurento::ObjectDestroyed> &event, JsonSerializer &s);
};

} /* kurento */

#endif /*  __OBJECT_DESTROYED_HPP__ */
