/* Autogenerated with kurento-module-creator */

#include "RTCCodec.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

namespace kurento
{

void RTCCodec::Serialize (JsonSerializer &s)
{
  RTCStats::Serialize (s);


  if (s.IsWriter) {
    s.JsonValue["__type__"] = "RTCCodec";
    s.JsonValue["__module__"] = "kurento";

    s.SerializeNVP (payloadType);

    s.SerializeNVP (codec);

    s.SerializeNVP (clockRate);

    s.SerializeNVP (channels);

    s.SerializeNVP (parameters);

  } else {
    if (!s.JsonValue.isMember ("payloadType") || !s.JsonValue["payloadType"].isConvertibleTo (Json::ValueType::int64Value) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'payloadType' property should be a int64");
    }

    s.SerializeNVP (payloadType);

    if (!s.JsonValue.isMember ("codec") || !s.JsonValue["codec"].isConvertibleTo (Json::ValueType::stringValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'codec' property should be a string");
    }

    s.SerializeNVP (codec);

    if (!s.JsonValue.isMember ("clockRate") || !s.JsonValue["clockRate"].isConvertibleTo (Json::ValueType::int64Value) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'clockRate' property should be a int64");
    }

    s.SerializeNVP (clockRate);

    if (!s.JsonValue.isMember ("channels") || !s.JsonValue["channels"].isConvertibleTo (Json::ValueType::int64Value) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'channels' property should be a int64");
    }

    s.SerializeNVP (channels);

    if (!s.JsonValue.isMember ("parameters") || !s.JsonValue["parameters"].isConvertibleTo (Json::ValueType::stringValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'parameters' property should be a string");
    }

    s.SerializeNVP (parameters);

  }
}

} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::RTCCodec> &object, JsonSerializer &s)
{
  if (!s.IsWriter && !object) {
    if (!s.JsonValue.isMember ("__type__") || !s.JsonValue["__type__"].isConvertibleTo (Json::ValueType::stringValue) || !s.JsonValue.isMember ("__module__") || !s.JsonValue["__module__"].isConvertibleTo (Json::ValueType::stringValue)) {
      object.reset (new kurento::RTCCodec() );
    } else {
      auto ptr = kurento::RegisterParent::createRegister (s.JsonValue["__module__"].asString () + "." + s.JsonValue["__type__"].asString ());

      if (!ptr) {
        throw KurentoException (UNEXPECTED_ERROR,
                                "Type " + s.JsonValue["__type__"].asString () + " does not exist in module " + s.JsonValue["__module__"].asString ());
      }

      object.reset (dynamic_cast <kurento::RTCCodec*> (ptr));

      if (!object) {
        delete ptr;
        throw KurentoException (UNEXPECTED_ERROR, "Type " + s.JsonValue["__type__"].asString () + " is not compatible");
      }
    }
  }

  if (object) {
    object->Serialize (s);
  }
}

} /* kurento */