/* Autogenerated with kurento-module-creator */

#ifndef __RTCCODEC_HPP__
#define __RTCCODEC_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include "RTCStats.hpp"


namespace kurento
{
class RTCCodec;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::RTCCodec> &object, JsonSerializer &s);
} /* kurento */

namespace kurento
{

class RTCCodec : public RTCStats
{

public:

  RTCCodec (const std::string &id, std::shared_ptr<StatsType> type, double timestamp, int64_t timestampMillis, int64_t payloadType, const std::string &codec, int64_t clockRate, int64_t channels, const std::string &parameters) : RTCStats (id, type, timestamp, timestampMillis) {
    this->payloadType = payloadType;
    this->codec = codec;
    this->clockRate = clockRate;
    this->channels = channels;
    this->parameters = parameters;
  };

  void setPayloadType (int64_t payloadType) {
    this->payloadType = payloadType;
  };

  int64_t getPayloadType () {
    return payloadType;
  };

  void setCodec (const std::string &codec) {
    this->codec = codec;
  };

  std::string getCodec () {
    return codec;
  };

  void setClockRate (int64_t clockRate) {
    this->clockRate = clockRate;
  };

  int64_t getClockRate () {
    return clockRate;
  };

  void setChannels (int64_t channels) {
    this->channels = channels;
  };

  int64_t getChannels () {
    return channels;
  };

  void setParameters (const std::string &parameters) {
    this->parameters = parameters;
  };

  std::string getParameters () {
    return parameters;
  };

  void Serialize (JsonSerializer &s) override;

  static void registerType () {
    std::function<RegisterParent*(void)> func =
        [] () {

      return new RTCCodec ();

    };

    RegisterParent::registerType ("kurento.RTCCodec", func);
  }

protected:

  RTCCodec() = default;

private:

  int64_t payloadType;
  std::string codec;
  int64_t clockRate;
  int64_t channels;
  std::string parameters;

  friend void kurento::Serialize (std::shared_ptr<kurento::RTCCodec> &object, JsonSerializer &s);

};

} /* kurento */

#endif /*  __RTCCODEC_HPP__ */
