/* Autogenerated with kurento-module-creator */

#include "RTCDataChannelState.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

namespace kurento
{

RTCDataChannelState::type RTCDataChannelState::getValueFromString (const std::string &value)
{

  if (value ==  "connecting") {
    return connecting;
  }

  if (value ==  "open") {
    return open;
  }

  if (value ==  "closing") {
    return closing;
  }

  if (value ==  "closed") {
    return closed;
  }

  throw KurentoException (MARSHALL_ERROR,
                          "Invalid value for 'RTCDataChannelState'");

}

void RTCDataChannelState::Serialize (JsonSerializer &s)
{
  if (s.IsWriter) {
    s.JsonValue = getString();
  } else {
    if (s.JsonValue.isConvertibleTo (Json::ValueType::stringValue) ) {
      enumValue = getValueFromString (s.JsonValue.asString() );
    } else {
      throw KurentoException (MARSHALL_ERROR,
                              "'RTCDataChannelState' type should be a string");
    }
  }
}

} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::RTCDataChannelState> &object, JsonSerializer &s)
{
  if (!s.IsWriter && !object) {
    object.reset (new kurento::RTCDataChannelState() );
  }

  if (object) {
    object->Serialize (s);
  }
}

} /* kurento */