/* Autogenerated with kurento-module-creator */

#include "RTCMediaStreamStats.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

namespace kurento
{

void RTCMediaStreamStats::Serialize (JsonSerializer &s)
{
  RTCStats::Serialize (s);


  if (s.IsWriter) {
    s.JsonValue["__type__"] = "RTCMediaStreamStats";
    s.JsonValue["__module__"] = "kurento";

    s.SerializeNVP (streamIdentifier);

    s.SerializeNVP (trackIds);

  } else {
    if (!s.JsonValue.isMember ("streamIdentifier") || !s.JsonValue["streamIdentifier"].isConvertibleTo (Json::ValueType::stringValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'streamIdentifier' property should be a string");
    }

    s.SerializeNVP (streamIdentifier);

    if (!s.JsonValue.isMember ("trackIds") || !s.JsonValue["trackIds"].isConvertibleTo (Json::ValueType::arrayValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'trackIds' property should be a list");
    }

    s.SerializeNVP (trackIds);

  }
}

} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::RTCMediaStreamStats> &object, JsonSerializer &s)
{
  if (!s.IsWriter && !object) {
    if (!s.JsonValue.isMember ("__type__") || !s.JsonValue["__type__"].isConvertibleTo (Json::ValueType::stringValue) || !s.JsonValue.isMember ("__module__") || !s.JsonValue["__module__"].isConvertibleTo (Json::ValueType::stringValue)) {
      object.reset (new kurento::RTCMediaStreamStats() );
    } else {
      auto ptr = kurento::RegisterParent::createRegister (s.JsonValue["__module__"].asString () + "." + s.JsonValue["__type__"].asString ());

      if (!ptr) {
        throw KurentoException (UNEXPECTED_ERROR,
                                "Type " + s.JsonValue["__type__"].asString () + " does not exist in module " + s.JsonValue["__module__"].asString ());
      }

      object.reset (dynamic_cast <kurento::RTCMediaStreamStats*> (ptr));

      if (!object) {
        delete ptr;
        throw KurentoException (UNEXPECTED_ERROR, "Type " + s.JsonValue["__type__"].asString () + " is not compatible");
      }
    }
  }

  if (object) {
    object->Serialize (s);
  }
}

} /* kurento */