/* Autogenerated with kurento-module-creator */

#include "RTCStatsIceCandidatePairState.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

namespace kurento
{

RTCStatsIceCandidatePairState::type RTCStatsIceCandidatePairState::getValueFromString (const std::string &value)
{

  if (value ==  "frozen") {
    return frozen;
  }

  if (value ==  "waiting") {
    return waiting;
  }

  if (value ==  "inprogress") {
    return inprogress;
  }

  if (value ==  "failed") {
    return failed;
  }

  if (value ==  "succeeded") {
    return succeeded;
  }

  if (value ==  "cancelled") {
    return cancelled;
  }

  throw KurentoException (MARSHALL_ERROR,
                          "Invalid value for 'RTCStatsIceCandidatePairState'");

}

void RTCStatsIceCandidatePairState::Serialize (JsonSerializer &s)
{
  if (s.IsWriter) {
    s.JsonValue = getString();
  } else {
    if (s.JsonValue.isConvertibleTo (Json::ValueType::stringValue) ) {
      enumValue = getValueFromString (s.JsonValue.asString() );
    } else {
      throw KurentoException (MARSHALL_ERROR,
                              "'RTCStatsIceCandidatePairState' type should be a string");
    }
  }
}

} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::RTCStatsIceCandidatePairState> &object, JsonSerializer &s)
{
  if (!s.IsWriter && !object) {
    object.reset (new kurento::RTCStatsIceCandidatePairState() );
  }

  if (object) {
    object->Serialize (s);
  }
}

} /* kurento */