/* Autogenerated with kurento-module-creator */

#ifndef __RTCSTATS_ICE_CANDIDATE_TYPE_HPP__
#define __RTCSTATS_ICE_CANDIDATE_TYPE_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>


namespace kurento
{
class RTCStatsIceCandidateType;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::RTCStatsIceCandidateType> &object, JsonSerializer &s);
} /* kurento */

namespace kurento
{

class RTCStatsIceCandidateType
{

public:

  typedef enum {
    host,
    serverreflexive,
    peerreflexive,
    relayed
  } type;

  RTCStatsIceCandidateType (const std::string &value) {
    enumValue = getValueFromString (value);
  };

  RTCStatsIceCandidateType (type value) {
    this->enumValue = value;
  }

  type getValue () {
    return enumValue;
  };

  std::string getString () {

    if (enumValue ==  host) {
      return "host";
    }

    if (enumValue ==  serverreflexive) {
      return "serverreflexive";
    }

    if (enumValue ==  peerreflexive) {
      return "peerreflexive";
    }

    if (enumValue ==  relayed) {
      return "relayed";
    }

    return "";
  }

  void Serialize (JsonSerializer &s);

  RTCStatsIceCandidateType() = default;

private:

  static type getValueFromString (const std::string &value);

  type enumValue;

  friend void kurento::Serialize (std::shared_ptr<kurento::RTCStatsIceCandidateType> &object, JsonSerializer &s);

};

} /* kurento */

#endif /*  __RTCSTATS_ICE_CANDIDATE_TYPE_HPP__ */
