/* Autogenerated with kurento-module-creator */

#ifndef __SDP_ENDPOINT_HPP__
#define __SDP_ENDPOINT_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "SessionEndpoint.hpp"

namespace kurento
{
class SdpEndpoint;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::SdpEndpoint> &object, JsonSerializer &serializer);
}

namespace kurento
{
class SdpEndpoint : public virtual SessionEndpoint
{

public:
  SdpEndpoint() = default;
  ~SdpEndpoint() override = default;


  virtual std::string generateOffer () = 0;
  virtual std::string processOffer (const std::string &offer) = 0;
  virtual std::string processAnswer (const std::string &answer) = 0;
  virtual std::string getLocalSessionDescriptor () = 0;
  virtual std::string getRemoteSessionDescriptor () = 0;

  const std::string &getType() const override;
  const std::string &getQualifiedType() const override;
  const std::string &getModule() const override;
  const std::vector<std::string> &getHierarchy() const override;

  void Serialize(JsonSerializer &serializer) override = 0;

  virtual int getMaxVideoRecvBandwidth () = 0;
  virtual void setMaxVideoRecvBandwidth (int maxVideoRecvBandwidth) = 0;

  virtual int getMaxAudioRecvBandwidth () = 0;
  virtual void setMaxAudioRecvBandwidth (int maxAudioRecvBandwidth) = 0;

};

} /* kurento */

#endif /*  __SDP_ENDPOINT_HPP__ */
