/* Autogenerated with kurento-module-creator */

#ifndef __SERVER_TYPE_HPP__
#define __SERVER_TYPE_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>


namespace kurento
{
class ServerType;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::ServerType> &object, JsonSerializer &s);
} /* kurento */

namespace kurento
{

class ServerType
{

public:

  typedef enum {
    KMS,
    KCS
  } type;

  ServerType (const std::string &value) {
    enumValue = getValueFromString (value);
  };

  ServerType (type value) {
    this->enumValue = value;
  }

  type getValue () {
    return enumValue;
  };

  std::string getString () {

    if (enumValue ==  KMS) {
      return "KMS";
    }

    if (enumValue ==  KCS) {
      return "KCS";
    }

    return "";
  }

  void Serialize (JsonSerializer &s);

  ServerType() = default;

private:

  static type getValueFromString (const std::string &value);

  type enumValue;

  friend void kurento::Serialize (std::shared_ptr<kurento::ServerType> &object, JsonSerializer &s);

};

} /* kurento */

#endif /*  __SERVER_TYPE_HPP__ */
