/* Autogenerated with kurento-module-creator */

#include "ServerManager.hpp"
#include <mutex>

namespace kurento
{

static std::vector<std::string> hierarchyServerManager;
std::once_flag initFlagServerManager;

static void
initHierarchy ()
{
  hierarchyServerManager.emplace_back("kurento.MediaObject");
}

const std::vector<std::string> &
ServerManager::getHierarchy () const
{
  std::call_once (initFlagServerManager,initHierarchy);
  return hierarchyServerManager;
}

const std::string&
ServerManager::getType () const {
  static std::string typeName = "ServerManager";

  return typeName;
}

const std::string&
ServerManager::getQualifiedType () const {
  static std::string qualifiedTypeName = getModule() + "." + getType();

  return qualifiedTypeName;
}

const std::string&
ServerManager::getModule () const {
  static std::string moduleName =  "kurento";

  return moduleName;
}

} /* kurento */
