/* Autogenerated with kurento-module-creator */

#include "ServerType.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

namespace kurento
{

ServerType::type ServerType::getValueFromString (const std::string &value)
{

  if (value ==  "KMS") {
    return KMS;
  }

  if (value ==  "KCS") {
    return KCS;
  }

  throw KurentoException (MARSHALL_ERROR,
                          "Invalid value for 'ServerType'");

}

void ServerType::Serialize (JsonSerializer &s)
{
  if (s.IsWriter) {
    s.JsonValue = getString();
  } else {
    if (s.JsonValue.isConvertibleTo (Json::ValueType::stringValue) ) {
      enumValue = getValueFromString (s.JsonValue.asString() );
    } else {
      throw KurentoException (MARSHALL_ERROR,
                              "'ServerType' type should be a string");
    }
  }
}

} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::ServerType> &object, JsonSerializer &s)
{
  if (!s.IsWriter && !object) {
    object.reset (new kurento::ServerType() );
  }

  if (object) {
    object->Serialize (s);
  }
}

} /* kurento */