/* Autogenerated with kurento-module-creator */

#include "ModuleInfo.hpp"
#include "ServerType.hpp"
#include "ServerInfo.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

namespace kurento
{

void ServerInfo::Serialize (JsonSerializer &s)
{

  if (s.IsWriter) {
    s.JsonValue["__type__"] = "ServerInfo";
    s.JsonValue["__module__"] = "kurento";

    s.SerializeNVP (version);

    s.SerializeNVP (modules);

    s.SerializeNVP (type);

    s.SerializeNVP (capabilities);

  } else {
    if (!s.JsonValue.isMember ("version") || !s.JsonValue["version"].isConvertibleTo (Json::ValueType::stringValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'version' property should be a string");
    }

    s.SerializeNVP (version);

    if (!s.JsonValue.isMember ("modules") || !s.JsonValue["modules"].isConvertibleTo (Json::ValueType::arrayValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'modules' property should be a list");
    }

    s.SerializeNVP (modules);

    if (!s.JsonValue.isMember ("type") || !s.JsonValue["type"].isConvertibleTo (Json::ValueType::stringValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'type' property should be a string");
    }

    s.SerializeNVP (type);

    if (!s.JsonValue.isMember ("capabilities") || !s.JsonValue["capabilities"].isConvertibleTo (Json::ValueType::arrayValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'capabilities' property should be a list");
    }

    s.SerializeNVP (capabilities);

  }
}

} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::ServerInfo> &object, JsonSerializer &s)
{
  if (!s.IsWriter && !object) {
    if (!s.JsonValue.isMember ("__type__") || !s.JsonValue["__type__"].isConvertibleTo (Json::ValueType::stringValue) || !s.JsonValue.isMember ("__module__") || !s.JsonValue["__module__"].isConvertibleTo (Json::ValueType::stringValue)) {
      object.reset (new kurento::ServerInfo() );
    } else {
      auto ptr = kurento::RegisterParent::createRegister (s.JsonValue["__module__"].asString () + "." + s.JsonValue["__type__"].asString ());

      if (!ptr) {
        throw KurentoException (UNEXPECTED_ERROR,
                                "Type " + s.JsonValue["__type__"].asString () + " does not exist in module " + s.JsonValue["__module__"].asString ());
      }

      object.reset (dynamic_cast <kurento::ServerInfo*> (ptr));

      if (!object) {
        delete ptr;
        throw KurentoException (UNEXPECTED_ERROR, "Type " + s.JsonValue["__type__"].asString () + " is not compatible");
      }
    }
  }

  if (object) {
    object->Serialize (s);
  }
}

} /* kurento */