/* Autogenerated with kurento-module-creator */

#ifndef __SESSION_ENDPOINT_INTERNAL_HPP__
#define __SESSION_ENDPOINT_INTERNAL_HPP__

#include "SessionEndpoint.hpp"

namespace kurento
{
class JsonSerializer;
}

namespace kurento
{

} /* kurento */

#endif /*  __SESSION_ENDPOINT_INTERNAL_HPP__ */
