/* Autogenerated with kurento-module-creator */

#include "SessionEndpoint.hpp"
#include <mutex>

namespace kurento
{

static std::vector<std::string> hierarchySessionEndpoint;
std::once_flag initFlagSessionEndpoint;

static void
initHierarchy ()
{
  hierarchySessionEndpoint.emplace_back("kurento.Endpoint");
  hierarchySessionEndpoint.emplace_back("kurento.MediaElement");
  hierarchySessionEndpoint.emplace_back("kurento.MediaObject");
}

const std::vector<std::string> &
SessionEndpoint::getHierarchy () const
{
  std::call_once (initFlagSessionEndpoint,initHierarchy);
  return hierarchySessionEndpoint;
}

const std::string&
SessionEndpoint::getType () const {
  static std::string typeName = "SessionEndpoint";

  return typeName;
}

const std::string&
SessionEndpoint::getQualifiedType () const {
  static std::string qualifiedTypeName = getModule() + "." + getType();

  return qualifiedTypeName;
}

const std::string&
SessionEndpoint::getModule () const {
  static std::string moduleName =  "kurento";

  return moduleName;
}

} /* kurento */
