/* Autogenerated with kurento-module-creator */

#include "StatsType.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

namespace kurento
{

StatsType::type StatsType::getValueFromString (const std::string &value)
{

  if (value ==  "inboundrtp") {
    return inboundrtp;
  }

  if (value ==  "outboundrtp") {
    return outboundrtp;
  }

  if (value ==  "session") {
    return session;
  }

  if (value ==  "datachannel") {
    return datachannel;
  }

  if (value ==  "track") {
    return track;
  }

  if (value ==  "transport") {
    return transport;
  }

  if (value ==  "candidatepair") {
    return candidatepair;
  }

  if (value ==  "localcandidate") {
    return localcandidate;
  }

  if (value ==  "remotecandidate") {
    return remotecandidate;
  }

  if (value ==  "element") {
    return element;
  }

  if (value ==  "endpoint") {
    return endpoint;
  }

  throw KurentoException (MARSHALL_ERROR,
                          "Invalid value for 'StatsType'");

}

void StatsType::Serialize (JsonSerializer &s)
{
  if (s.IsWriter) {
    s.JsonValue = getString();
  } else {
    if (s.JsonValue.isConvertibleTo (Json::ValueType::stringValue) ) {
      enumValue = getValueFromString (s.JsonValue.asString() );
    } else {
      throw KurentoException (MARSHALL_ERROR,
                              "'StatsType' type should be a string");
    }
  }
}

} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::StatsType> &object, JsonSerializer &s)
{
  if (!s.IsWriter && !object) {
    object.reset (new kurento::StatsType() );
  }

  if (object) {
    object->Serialize (s);
  }
}

} /* kurento */