/* Autogenerated with kurento-module-creator */

#ifndef __URI_ENDPOINT_STATE_HPP__
#define __URI_ENDPOINT_STATE_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>


namespace kurento
{
class UriEndpointState;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::UriEndpointState> &object, JsonSerializer &s);
} /* kurento */

namespace kurento
{

class UriEndpointState
{

public:

  typedef enum {
    STOP,
    START,
    PAUSE
  } type;

  UriEndpointState (const std::string &value) {
    enumValue = getValueFromString (value);
  };

  UriEndpointState (type value) {
    this->enumValue = value;
  }

  type getValue () {
    return enumValue;
  };

  std::string getString () {

    if (enumValue ==  STOP) {
      return "STOP";
    }

    if (enumValue ==  START) {
      return "START";
    }

    if (enumValue ==  PAUSE) {
      return "PAUSE";
    }

    return "";
  }

  void Serialize (JsonSerializer &s);

  UriEndpointState() = default;

private:

  static type getValueFromString (const std::string &value);

  type enumValue;

  friend void kurento::Serialize (std::shared_ptr<kurento::UriEndpointState> &object, JsonSerializer &s);

};

} /* kurento */

#endif /*  __URI_ENDPOINT_STATE_HPP__ */
