/* Autogenerated with kurento-module-creator */

#include "UriEndpointState.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

namespace kurento
{

UriEndpointState::type UriEndpointState::getValueFromString (const std::string &value)
{

  if (value ==  "STOP") {
    return STOP;
  }

  if (value ==  "START") {
    return START;
  }

  if (value ==  "PAUSE") {
    return PAUSE;
  }

  throw KurentoException (MARSHALL_ERROR,
                          "Invalid value for 'UriEndpointState'");

}

void UriEndpointState::Serialize (JsonSerializer &s)
{
  if (s.IsWriter) {
    s.JsonValue = getString();
  } else {
    if (s.JsonValue.isConvertibleTo (Json::ValueType::stringValue) ) {
      enumValue = getValueFromString (s.JsonValue.asString() );
    } else {
      throw KurentoException (MARSHALL_ERROR,
                              "'UriEndpointState' type should be a string");
    }
  }
}

} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::UriEndpointState> &object, JsonSerializer &s)
{
  if (!s.IsWriter && !object) {
    object.reset (new kurento::UriEndpointState() );
  }

  if (object) {
    object->Serialize (s);
  }
}

} /* kurento */