/* Autogenerated with kurento-module-creator */

#ifndef __URI_ENDPOINT_HPP__
#define __URI_ENDPOINT_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "Endpoint.hpp"
#include "UriEndpointStateChanged.hpp"
#include <sigc++/sigc++.h>

namespace kurento
{
class UriEndpoint;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::UriEndpoint> &object, JsonSerializer &serializer);
}

namespace kurento
{
class UriEndpointState;
} /* kurento */

namespace kurento
{
class UriEndpoint : public virtual Endpoint
{

public:
  UriEndpoint() = default;
  ~UriEndpoint() override = default;


  virtual void pause () = 0;
  virtual void stop () = 0;

  const std::string &getType() const override;
  const std::string &getQualifiedType() const override;
  const std::string &getModule() const override;
  const std::vector<std::string> &getHierarchy() const override;

  void Serialize(JsonSerializer &serializer) override = 0;

  virtual std::string getUri () = 0;

  virtual std::shared_ptr<UriEndpointState> getState () = 0;

};

} /* kurento */

#endif /*  __URI_ENDPOINT_HPP__ */
