/* Autogenerated with kurento-module-creator */

#include "VideoCodec.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

namespace kurento
{

VideoCodec::type VideoCodec::getValueFromString (const std::string &value)
{

  if (value ==  "VP8") {
    return VP8;
  }

  if (value ==  "H264") {
    return H264;
  }

  if (value ==  "RAW") {
    return RAW;
  }

  throw KurentoException (MARSHALL_ERROR,
                          "Invalid value for 'VideoCodec'");

}

void VideoCodec::Serialize (JsonSerializer &s)
{
  if (s.IsWriter) {
    s.JsonValue = getString();
  } else {
    if (s.JsonValue.isConvertibleTo (Json::ValueType::stringValue) ) {
      enumValue = getValueFromString (s.JsonValue.asString() );
    } else {
      throw KurentoException (MARSHALL_ERROR,
                              "'VideoCodec' type should be a string");
    }
  }
}

} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::VideoCodec> &object, JsonSerializer &s)
{
  if (!s.IsWriter && !object) {
    object.reset (new kurento::VideoCodec() );
  }

  if (object) {
    object->Serialize (s);
  }
}

} /* kurento */