# CMake generated Testfile for 
# Source directory: /root/workSpace/kms-omni-build/kurento-media-server/test
# Build directory: /root/workSpace/kms-omni-build/build-Debug/kurento-media-server/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_server_json "/root/workSpace/kms-omni-build/build-Debug/kurento-media-server/test/test_server_json")
set_tests_properties(test_server_json PROPERTIES  ENVIRONMENT "MEDIA_SERVER_CONF_FILE=/root/workSpace/kms-omni-build/kurento-media-server/test/../kurento.conf.json;SERVER_DIR=/root/workSpace/kms-omni-build/build-Debug/kurento-media-server/test/../server/kurento-media-server;GST_PLUGIN_PATH=:/root/workSpace/kms-omni-build/build-Debug;KURENTO_MODULES_PATH=:/root/workSpace/kms-omni-build/build-Debug;BOOST_TEST_CATCH_SYSTEM_ERRORS=no")
add_test(test_server_events "/root/workSpace/kms-omni-build/build-Debug/kurento-media-server/test/test_server_events")
set_tests_properties(test_server_events PROPERTIES  ENVIRONMENT "MEDIA_SERVER_CONF_FILE=/root/workSpace/kms-omni-build/kurento-media-server/test/../kurento.conf.json;SERVER_DIR=/root/workSpace/kms-omni-build/build-Debug/kurento-media-server/test/../server/kurento-media-server;GST_PLUGIN_PATH=:/root/workSpace/kms-omni-build/build-Debug;KURENTO_MODULES_PATH=:/root/workSpace/kms-omni-build/build-Debug;BOOST_TEST_CATCH_SYSTEM_ERRORS=no")
add_test(test_server_json_session "/root/workSpace/kms-omni-build/build-Debug/kurento-media-server/test/test_server_json_session")
set_tests_properties(test_server_json_session PROPERTIES  ENVIRONMENT "MEDIA_SERVER_CONF_FILE=/root/workSpace/kms-omni-build/kurento-media-server/test/../kurento.conf.json;SERVER_DIR=/root/workSpace/kms-omni-build/build-Debug/kurento-media-server/test/../server/kurento-media-server;GST_PLUGIN_PATH=:/root/workSpace/kms-omni-build/build-Debug;KURENTO_MODULES_PATH=:/root/workSpace/kms-omni-build/build-Debug;BOOST_TEST_CATCH_SYSTEM_ERRORS=no")
add_test(test_server_duplicate_requests "/root/workSpace/kms-omni-build/build-Debug/kurento-media-server/test/test_server_duplicate_requests")
set_tests_properties(test_server_duplicate_requests PROPERTIES  ENVIRONMENT "MEDIA_SERVER_CONF_FILE=/root/workSpace/kms-omni-build/kurento-media-server/test/../kurento.conf.json;SERVER_DIR=/root/workSpace/kms-omni-build/build-Debug/kurento-media-server/test/../server/kurento-media-server;GST_PLUGIN_PATH=:/root/workSpace/kms-omni-build/build-Debug;KURENTO_MODULES_PATH=:/root/workSpace/kms-omni-build/build-Debug;BOOST_TEST_CATCH_SYSTEM_ERRORS=no")
add_test(test_config_read "/root/workSpace/kms-omni-build/build-Debug/kurento-media-server/test/test_config_read")
set_tests_properties(test_config_read PROPERTIES  ENVIRONMENT "MEDIA_SERVER_CONF_FILE=/root/workSpace/kms-omni-build/kurento-media-server/test/../kurento.conf.json;SERVER_DIR=/root/workSpace/kms-omni-build/build-Debug/kurento-media-server/test/../server/kurento-media-server;GST_PLUGIN_PATH=:/root/workSpace/kms-omni-build/build-Debug;KURENTO_MODULES_PATH=:/root/workSpace/kms-omni-build/build-Debug;BOOST_TEST_CATCH_SYSTEM_ERRORS=no")
add_test(test_registrar "/root/workSpace/kms-omni-build/build-Debug/kurento-media-server/test/test_registrar")
set_tests_properties(test_registrar PROPERTIES  ENVIRONMENT "MEDIA_SERVER_CONF_FILE=/root/workSpace/kms-omni-build/kurento-media-server/test/../kurento.conf.json;SERVER_DIR=/root/workSpace/kms-omni-build/build-Debug/kurento-media-server/test/../server/kurento-media-server;GST_PLUGIN_PATH=:/root/workSpace/kms-omni-build/build-Debug;KURENTO_MODULES_PATH=:/root/workSpace/kms-omni-build/build-Debug;BOOST_TEST_CATCH_SYSTEM_ERRORS=no")
