/* Autogenerated with kurento-module-creator */

#ifndef __ENDPOINT_IMPL_FACTORY_HPP__
#define __ENDPOINT_IMPL_FACTORY_HPP__

#include "EndpointImpl.hpp"
#include "MediaElementImplFactory.hpp"
#include <Factory.hpp>
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{

class EndpointImplFactory : public virtual MediaElementImplFactory
{
public:
  EndpointImplFactory() = default;

  std::string getName() const override {
    return "Endpoint";
  };

};

} /* kurento */

#endif /*  __ENDPOINT_IMPL_FACTORY_HPP__ */
