/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "FilterImpl.hpp"
#include "FilterImplFactory.hpp"
#include "FilterInternal.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

using kurento::KurentoException;

namespace kurento
{

void
FilterImpl::invoke (std::shared_ptr<MediaObjectImpl> obj, const std::string &methodName, const Json::Value &params, Json::Value &response)
{
  MediaElementImpl::invoke (obj, methodName, params, response);
}

bool
FilterImpl::connect (const std::string &eventType, std::shared_ptr<EventHandler> handler)
{

  return MediaElementImpl::connect (eventType, handler);
}

void
FilterImpl::Serialize (JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    try {
      Json::Value v (getId() );

      serializer.JsonValue = v;
    } catch (std::bad_cast &e) {
    }
  } else {
    throw KurentoException (MARSHALL_ERROR,
                            "'FilterImpl' cannot be deserialized as an object");
  }
}
} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::FilterImpl> &object, JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    if (object) {
      object->Serialize (serializer);
    }
  } else {
    std::shared_ptr<kurento::MediaObjectImpl> aux;
    aux = kurento::FilterImplFactory::getObject (JsonFixes::getString(serializer.JsonValue) );
    object = std::dynamic_pointer_cast<kurento::FilterImpl> (aux);
  }
}

void
Serialize (std::shared_ptr<kurento::Filter> &object, JsonSerializer &serializer)
{
  std::shared_ptr<kurento::FilterImpl> aux = std::dynamic_pointer_cast<kurento::FilterImpl> (object);

  Serialize (aux, serializer);
  object = std::dynamic_pointer_cast <kurento::Filter> (aux);
}

} /* kurento */