/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "GstreamerDotDetails.hpp"
#include "HubImpl.hpp"
#include "HubImplFactory.hpp"
#include "HubInternal.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

using kurento::KurentoException;

namespace kurento
{

void
HubImpl::invoke (std::shared_ptr<MediaObjectImpl> obj, const std::string &methodName, const Json::Value &params, Json::Value &response)
{
  if (methodName == "getGstreamerDot") {
    kurento::JsonSerializer s (false);
    HubMethodGetGstreamerDot method;
    JsonSerializer responseSerializer (true);
    std::string ret;

    s.JsonValue = params;
    method.Serialize (s);

    ret = method.invoke (std::dynamic_pointer_cast<Hub> (obj) );
    responseSerializer.SerializeNVP (ret);
    response = responseSerializer.JsonValue["ret"];
    return;
  }

  MediaObjectImpl::invoke (obj, methodName, params, response);
}

bool
HubImpl::connect (const std::string &eventType, std::shared_ptr<EventHandler> handler)
{

  return MediaObjectImpl::connect (eventType, handler);
}

void
HubImpl::Serialize (JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    try {
      Json::Value v (getId() );

      serializer.JsonValue = v;
    } catch (std::bad_cast &e) {
    }
  } else {
    throw KurentoException (MARSHALL_ERROR,
                            "'HubImpl' cannot be deserialized as an object");
  }
}
} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::HubImpl> &object, JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    if (object) {
      object->Serialize (serializer);
    }
  } else {
    std::shared_ptr<kurento::MediaObjectImpl> aux;
    aux = kurento::HubImplFactory::getObject (JsonFixes::getString(serializer.JsonValue) );
    object = std::dynamic_pointer_cast<kurento::HubImpl> (aux);
  }
}

void
Serialize (std::shared_ptr<kurento::Hub> &object, JsonSerializer &serializer)
{
  std::shared_ptr<kurento::HubImpl> aux = std::dynamic_pointer_cast<kurento::HubImpl> (object);

  Serialize (aux, serializer);
  object = std::dynamic_pointer_cast <kurento::Hub> (aux);
}

} /* kurento */