/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "HubImpl.hpp"
#include "HubPortImpl.hpp"
#include "HubPortImplFactory.hpp"
#include "HubPortInternal.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

using kurento::KurentoException;

namespace kurento
{

MediaObjectImpl *HubPortImplFactory::createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const
{
  kurento::JsonSerializer s (false);
  HubPortConstructor constructor;

  s.JsonValue = params;
  constructor.Serialize (s);

  return createObject (conf, constructor.getHub() );
}

void
HubPortImpl::invoke (std::shared_ptr<MediaObjectImpl> obj, const std::string &methodName, const Json::Value &params, Json::Value &response)
{
  MediaElementImpl::invoke (obj, methodName, params, response);
}

bool
HubPortImpl::connect (const std::string &eventType, std::shared_ptr<EventHandler> handler)
{

  return MediaElementImpl::connect (eventType, handler);
}

void
HubPortImpl::Serialize (JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    try {
      Json::Value v (getId() );

      serializer.JsonValue = v;
    } catch (std::bad_cast &e) {
    }
  } else {
    throw KurentoException (MARSHALL_ERROR,
                            "'HubPortImpl' cannot be deserialized as an object");
  }
}
} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::HubPortImpl> &object, JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    if (object) {
      object->Serialize (serializer);
    }
  } else {
    std::shared_ptr<kurento::MediaObjectImpl> aux;
    aux = kurento::HubPortImplFactory::getObject (JsonFixes::getString(serializer.JsonValue) );
    object = std::dynamic_pointer_cast<kurento::HubPortImpl> (aux);
  }
}

void
Serialize (std::shared_ptr<kurento::HubPort> &object, JsonSerializer &serializer)
{
  std::shared_ptr<kurento::HubPortImpl> aux = std::dynamic_pointer_cast<kurento::HubPortImpl> (object);

  Serialize (aux, serializer);
  object = std::dynamic_pointer_cast <kurento::HubPort> (aux);
}

} /* kurento */