/* Autogenerated with kurento-module-creator */

#ifndef __MEDIA_ELEMENT_IMPL_FACTORY_HPP__
#define __MEDIA_ELEMENT_IMPL_FACTORY_HPP__

#include "MediaElementImpl.hpp"
#include "MediaObjectImplFactory.hpp"
#include <Factory.hpp>
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{

class MediaElementImplFactory : public virtual MediaObjectImplFactory
{
public:
  MediaElementImplFactory() = default;

  std::string getName() const override {
    return "MediaElement";
  };

};

} /* kurento */

#endif /*  __MEDIA_ELEMENT_IMPL_FACTORY_HPP__ */
