/* Autogenerated with kurento-module-creator */

#ifndef __MEDIA_PIPELINE_IMPL_FACTORY_HPP__
#define __MEDIA_PIPELINE_IMPL_FACTORY_HPP__

#include "MediaPipelineImpl.hpp"
#include "MediaObjectImplFactory.hpp"
#include <Factory.hpp>
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{

class MediaPipelineImplFactory : public virtual MediaObjectImplFactory
{
public:
  MediaPipelineImplFactory() = default;

  std::string getName() const override {
    return "MediaPipeline";
  };

private:

  MediaObjectImpl *createObjectPointer (
      const boost::property_tree::ptree &conf,
      const Json::Value &params) const override;

  MediaObjectImpl *createObject (const boost::property_tree::ptree &conf) const;
};

} /* kurento */

#endif /*  __MEDIA_PIPELINE_IMPL_FACTORY_HPP__ */
