/* Autogenerated with kurento-module-creator */

#ifndef __MEDIA_OBJECT_IMPL_FACTORY_HPP__
#define __MEDIA_OBJECT_IMPL_FACTORY_HPP__

#include "MediaObjectImpl.hpp"
#include <Factory.hpp>
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{

class MediaObjectImplFactory : public virtual kurento::Factory
{
public:
  MediaObjectImplFactory() = default;

  std::string getName() const override {
    return "MediaObject";
  };

};

} /* kurento */

#endif /*  __MEDIA_OBJECT_IMPL_FACTORY_HPP__ */
