/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipelineImpl.hpp"
#include "PassThroughImpl.hpp"
#include "PassThroughImplFactory.hpp"
#include "PassThroughInternal.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

using kurento::KurentoException;

namespace kurento
{

MediaObjectImpl *PassThroughImplFactory::createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const
{
  kurento::JsonSerializer s (false);
  PassThroughConstructor constructor;

  s.JsonValue = params;
  constructor.Serialize (s);

  return createObject (conf, constructor.getMediaPipeline() );
}

void
PassThroughImpl::invoke (std::shared_ptr<MediaObjectImpl> obj, const std::string &methodName, const Json::Value &params, Json::Value &response)
{
  MediaElementImpl::invoke (obj, methodName, params, response);
}

bool
PassThroughImpl::connect (const std::string &eventType, std::shared_ptr<EventHandler> handler)
{

  return MediaElementImpl::connect (eventType, handler);
}

void
PassThroughImpl::Serialize (JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    try {
      Json::Value v (getId() );

      serializer.JsonValue = v;
    } catch (std::bad_cast &e) {
    }
  } else {
    throw KurentoException (MARSHALL_ERROR,
                            "'PassThroughImpl' cannot be deserialized as an object");
  }
}
} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::PassThroughImpl> &object, JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    if (object) {
      object->Serialize (serializer);
    }
  } else {
    std::shared_ptr<kurento::MediaObjectImpl> aux;
    aux = kurento::PassThroughImplFactory::getObject (JsonFixes::getString(serializer.JsonValue) );
    object = std::dynamic_pointer_cast<kurento::PassThroughImpl> (aux);
  }
}

void
Serialize (std::shared_ptr<kurento::PassThrough> &object, JsonSerializer &serializer)
{
  std::shared_ptr<kurento::PassThroughImpl> aux = std::dynamic_pointer_cast<kurento::PassThroughImpl> (object);

  Serialize (aux, serializer);
  object = std::dynamic_pointer_cast <kurento::PassThrough> (aux);
}

} /* kurento */