/* Autogenerated with kurento-module-creator */

#ifndef __SDP_ENDPOINT_IMPL_FACTORY_HPP__
#define __SDP_ENDPOINT_IMPL_FACTORY_HPP__

#include "SdpEndpointImpl.hpp"
#include "SessionEndpointImplFactory.hpp"
#include <Factory.hpp>
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{

class SdpEndpointImplFactory : public virtual SessionEndpointImplFactory
{
public:
  SdpEndpointImplFactory() = default;

  std::string getName() const override {
    return "SdpEndpoint";
  };

};

} /* kurento */

#endif /*  __SDP_ENDPOINT_IMPL_FACTORY_HPP__ */
