/* Autogenerated with kurento-module-creator */

#ifndef __SESSION_ENDPOINT_IMPL_FACTORY_HPP__
#define __SESSION_ENDPOINT_IMPL_FACTORY_HPP__

#include "SessionEndpointImpl.hpp"
#include "EndpointImplFactory.hpp"
#include <Factory.hpp>
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{

class SessionEndpointImplFactory : public virtual EndpointImplFactory
{
public:
  SessionEndpointImplFactory() = default;

  std::string getName() const override {
    return "SessionEndpoint";
  };

};

} /* kurento */

#endif /*  __SESSION_ENDPOINT_IMPL_FACTORY_HPP__ */
