/* Autogenerated with kurento-module-creator */

#ifndef __URI_ENDPOINT_IMPL_FACTORY_HPP__
#define __URI_ENDPOINT_IMPL_FACTORY_HPP__

#include "UriEndpointImpl.hpp"
#include "EndpointImplFactory.hpp"
#include <Factory.hpp>
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{

class UriEndpointImplFactory : public virtual EndpointImplFactory
{
public:
  UriEndpointImplFactory() = default;

  std::string getName() const override {
    return "UriEndpoint";
  };

};

} /* kurento */

#endif /*  __URI_ENDPOINT_IMPL_FACTORY_HPP__ */
