/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include "ImageOverlayFilterImpl.hpp"
#include "ImageOverlayFilterImplFactory.hpp"
#include "ImageOverlayFilterInternal.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

using kurento::KurentoException;

namespace kurento
{

MediaObjectImpl *ImageOverlayFilterImplFactory::createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const
{
  kurento::JsonSerializer s (false);
  ImageOverlayFilterConstructor constructor;

  s.JsonValue = params;
  constructor.Serialize (s);

  return createObject (conf, constructor.getMediaPipeline() );
}

void
ImageOverlayFilterImpl::invoke (std::shared_ptr<MediaObjectImpl> obj, const std::string &methodName, const Json::Value &params, Json::Value &response)
{
  if (methodName == "removeImage") {
    kurento::JsonSerializer s (false);
    ImageOverlayFilterMethodRemoveImage method;

    s.JsonValue = params;
    method.Serialize (s);

    method.invoke (std::dynamic_pointer_cast<ImageOverlayFilter> (obj) );
    return;
  }

  if (methodName == "addImage") {
    kurento::JsonSerializer s (false);
    ImageOverlayFilterMethodAddImage method;

    s.JsonValue = params;
    method.Serialize (s);

    method.invoke (std::dynamic_pointer_cast<ImageOverlayFilter> (obj) );
    return;
  }

  FilterImpl::invoke (obj, methodName, params, response);
}

bool
ImageOverlayFilterImpl::connect (const std::string &eventType, std::shared_ptr<EventHandler> handler)
{

  return FilterImpl::connect (eventType, handler);
}

void
ImageOverlayFilterImpl::Serialize (JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    try {
      Json::Value v (getId() );

      serializer.JsonValue = v;
    } catch (std::bad_cast &e) {
    }
  } else {
    throw KurentoException (MARSHALL_ERROR,
                            "'ImageOverlayFilterImpl' cannot be deserialized as an object");
  }
}
} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::ImageOverlayFilterImpl> &object, JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    if (object) {
      object->Serialize (serializer);
    }
  } else {
    std::shared_ptr<kurento::MediaObjectImpl> aux;
    aux = kurento::ImageOverlayFilterImplFactory::getObject (JsonFixes::getString(serializer.JsonValue) );
    object = std::dynamic_pointer_cast<kurento::ImageOverlayFilterImpl> (aux);
  }
}

void
Serialize (std::shared_ptr<kurento::ImageOverlayFilter> &object, JsonSerializer &serializer)
{
  std::shared_ptr<kurento::ImageOverlayFilterImpl> aux = std::dynamic_pointer_cast<kurento::ImageOverlayFilterImpl> (object);

  Serialize (aux, serializer);
  object = std::dynamic_pointer_cast <kurento::ImageOverlayFilter> (aux);
}

} /* kurento */