/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include "ZBarFilterImpl.hpp"
#include "ZBarFilterImplFactory.hpp"
#include "ZBarFilterInternal.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

using kurento::KurentoException;

namespace kurento
{

MediaObjectImpl *ZBarFilterImplFactory::createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const
{
  kurento::JsonSerializer s (false);
  ZBarFilterConstructor constructor;

  s.JsonValue = params;
  constructor.Serialize (s);

  return createObject (conf, constructor.getMediaPipeline() );
}

void
ZBarFilterImpl::invoke (std::shared_ptr<MediaObjectImpl> obj, const std::string &methodName, const Json::Value &params, Json::Value &response)
{
  FilterImpl::invoke (obj, methodName, params, response);
}

bool
ZBarFilterImpl::connect (const std::string &eventType, std::shared_ptr<EventHandler> handler)
{

  if ("CodeFound" == eventType) {
    std::weak_ptr<EventHandler> wh = handler;

    sigc::connection conn = signalCodeFound.connect ([ &, wh] (CodeFound event) {
      std::shared_ptr<EventHandler> lh = wh.lock();
      if (!lh)
        return;

      std::shared_ptr<CodeFound> ev_ref (new CodeFound(event));
      auto object = this->shared_from_this();

      lh->sendEventAsync ([ev_ref, object, lh] {
        JsonSerializer s (true);

        s.Serialize ("data", ev_ref.get());
        s.Serialize ("object", object.get());
        s.JsonValue["type"] = "CodeFound";

        lh->sendEvent (s.JsonValue);
      });
    });
    handler->setConnection (conn);
    return true;
  }

  return FilterImpl::connect (eventType, handler);
}

void
ZBarFilterImpl::Serialize (JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    try {
      Json::Value v (getId() );

      serializer.JsonValue = v;
    } catch (std::bad_cast &e) {
    }
  } else {
    throw KurentoException (MARSHALL_ERROR,
                            "'ZBarFilterImpl' cannot be deserialized as an object");
  }
}
} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::ZBarFilterImpl> &object, JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    if (object) {
      object->Serialize (serializer);
    }
  } else {
    std::shared_ptr<kurento::MediaObjectImpl> aux;
    aux = kurento::ZBarFilterImplFactory::getObject (JsonFixes::getString(serializer.JsonValue) );
    object = std::dynamic_pointer_cast<kurento::ZBarFilterImpl> (aux);
  }
}

void
Serialize (std::shared_ptr<kurento::ZBarFilter> &object, JsonSerializer &serializer)
{
  std::shared_ptr<kurento::ZBarFilterImpl> aux = std::dynamic_pointer_cast<kurento::ZBarFilterImpl> (object);

  Serialize (aux, serializer);
  object = std::dynamic_pointer_cast <kurento::ZBarFilter> (aux);
}

} /* kurento */