# Autogenerated with kurento-module-creator
cmake_minimum_required(VERSION 2.8)

include (GenericFind)

###############################################################
# Dependencies
###############################################################
# looking for core dependencies
generic_find (
  REQUIRED
  LIBNAME KMSCORE
  VERSION ^6.7.0
)

set (KMSELEMENTS_DEPENDENCIES_LIBRARIES
  ${KMSCORE_LIBRARIES}
  CACHE INTERNAL "Model library dependencies"
)

set (KMSELEMENTS_DEPENDENCIES_INCLUDE_DIRS
  ${KMSCORE_INCLUDE_DIRS}
  CACHE INTERNAL "Model library dependencies"
)
