/* Autogenerated with kurento-module-creator */

#ifndef __CERTIFICATE_KEY_TYPE_HPP__
#define __CERTIFICATE_KEY_TYPE_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>


namespace kurento
{
class CertificateKeyType;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::CertificateKeyType> &object, JsonSerializer &s);
} /* kurento */

namespace kurento
{

class CertificateKeyType
{

public:

  typedef enum {
    RSA,
    ECDSA
  } type;

  CertificateKeyType (const std::string &value) {
    enumValue = getValueFromString (value);
  };

  CertificateKeyType (type value) {
    this->enumValue = value;
  }

  type getValue () {
    return enumValue;
  };

  std::string getString () {

    if (enumValue ==  RSA) {
      return "RSA";
    }

    if (enumValue ==  ECDSA) {
      return "ECDSA";
    }

    return "";
  }

  void Serialize (JsonSerializer &s);

  CertificateKeyType() = default;

private:

  static type getValueFromString (const std::string &value);

  type enumValue;

  friend void kurento::Serialize (std::shared_ptr<kurento::CertificateKeyType> &object, JsonSerializer &s);

};

} /* kurento */

#endif /*  __CERTIFICATE_KEY_TYPE_HPP__ */
