/* Autogenerated with kurento-module-creator */

#include "CertificateKeyType.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

namespace kurento
{

CertificateKeyType::type CertificateKeyType::getValueFromString (const std::string &value)
{

  if (value ==  "RSA") {
    return RSA;
  }

  if (value ==  "ECDSA") {
    return ECDSA;
  }

  throw KurentoException (MARSHALL_ERROR,
                          "Invalid value for 'CertificateKeyType'");

}

void CertificateKeyType::Serialize (JsonSerializer &s)
{
  if (s.IsWriter) {
    s.JsonValue = getString();
  } else {
    if (s.JsonValue.isConvertibleTo (Json::ValueType::stringValue) ) {
      enumValue = getValueFromString (s.JsonValue.asString() );
    } else {
      throw KurentoException (MARSHALL_ERROR,
                              "'CertificateKeyType' type should be a string");
    }
  }
}

} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::CertificateKeyType> &object, JsonSerializer &s)
{
  if (!s.IsWriter && !object) {
    object.reset (new kurento::CertificateKeyType() );
  }

  if (object) {
    object->Serialize (s);
  }
}

} /* kurento */