/* Autogenerated with kurento-module-creator */

#include "Composite.hpp"
#include <mutex>

namespace kurento
{

static std::vector<std::string> hierarchyComposite;
std::once_flag initFlagComposite;

static void
initHierarchy ()
{
  hierarchyComposite.emplace_back("kurento.Hub");
  hierarchyComposite.emplace_back("kurento.MediaObject");
}

const std::vector<std::string> &
Composite::getHierarchy () const
{
  std::call_once (initFlagComposite,initHierarchy);
  return hierarchyComposite;
}

const std::string&
Composite::getType () const {
  static std::string typeName = "Composite";

  return typeName;
}

const std::string&
Composite::getQualifiedType () const {
  static std::string qualifiedTypeName = getModule() + "." + getType();

  return qualifiedTypeName;
}

const std::string&
Composite::getModule () const {
  static std::string moduleName =  "kurento";

  return moduleName;
}

} /* kurento */
