/* Autogenerated with kurento-module-creator */

#ifndef __DATA_CHANNEL_CLOSE_HPP__
#define __DATA_CHANNEL_CLOSE_HPP__

#include <json/json.h>
#include <memory>
#include "Media.hpp"

namespace kurento
{
class DataChannelClose;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::DataChannelClose> &object, JsonSerializer &s);
}


namespace kurento
{

class DataChannelClose : public Media
{

public:

  DataChannelClose (std::shared_ptr<MediaObject> source, const std::string &type, int channelId) : Media (source, type) {
      this->channelId = channelId;
  };

  DataChannelClose (const DataChannelClose &copy) : Media (copy) {
      this->channelId = copy.channelId;
  };

  DataChannelClose (const Json::Value &value);

  virtual void setChannelId (int channelId) {
    this->channelId = channelId;
  };

  virtual int getChannelId () {
    return channelId;
  };

  static std::string getName() {
    return "DataChannelClose";
  }

  void Serialize (JsonSerializer &s) override;

protected:

  DataChannelClose() = default;

private:
  int channelId;

  friend void kurento::Serialize (std::shared_ptr<kurento::DataChannelClose> &event, JsonSerializer &s);
};

} /* kurento */

#endif /*  __DATA_CHANNEL_CLOSE_HPP__ */
