/* Autogenerated with kurento-module-creator */

#include "DataChannelClose.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <chrono>
#include <ctime>
#include <string>

namespace kurento
{

void
DataChannelClose::Serialize (JsonSerializer &s)
{
  Media::Serialize (s);

  s.SerializeNVP (channelId);
}

} /* kurento */

namespace kurento
{

void Serialize (std::shared_ptr<kurento::DataChannelClose> &event, JsonSerializer &s)
{
  if (!s.IsWriter && !event) {
    event.reset (new kurento::DataChannelClose() );
  }

  if (event) {
    event->Serialize (s);
  }
}

} /* kurento */
