/* Autogenerated with kurento-module-creator */

#include "DispatcherOneToMany.hpp"
#include <mutex>

namespace kurento
{

static std::vector<std::string> hierarchyDispatcherOneToMany;
std::once_flag initFlagDispatcherOneToMany;

static void
initHierarchy ()
{
  hierarchyDispatcherOneToMany.emplace_back("kurento.Hub");
  hierarchyDispatcherOneToMany.emplace_back("kurento.MediaObject");
}

const std::vector<std::string> &
DispatcherOneToMany::getHierarchy () const
{
  std::call_once (initFlagDispatcherOneToMany,initHierarchy);
  return hierarchyDispatcherOneToMany;
}

const std::string&
DispatcherOneToMany::getType () const {
  static std::string typeName = "DispatcherOneToMany";

  return typeName;
}

const std::string&
DispatcherOneToMany::getQualifiedType () const {
  static std::string qualifiedTypeName = getModule() + "." + getType();

  return qualifiedTypeName;
}

const std::string&
DispatcherOneToMany::getModule () const {
  static std::string moduleName =  "kurento";

  return moduleName;
}

} /* kurento */
