/* Autogenerated with kurento-module-creator */

#ifndef __END_OF_STREAM_HPP__
#define __END_OF_STREAM_HPP__

#include <json/json.h>
#include <memory>
#include "Media.hpp"

namespace kurento
{
class EndOfStream;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::EndOfStream> &object, JsonSerializer &s);
}


namespace kurento
{

class EndOfStream : public Media
{

public:

  EndOfStream (std::shared_ptr<MediaObject> source, const std::string &type) : Media (source, type) {
  };

  EndOfStream (const EndOfStream &copy) : Media (copy) {
  };

  EndOfStream (const Json::Value &value);

  static std::string getName() {
    return "EndOfStream";
  }

  void Serialize (JsonSerializer &s) override;

protected:

  EndOfStream() = default;

private:

  friend void kurento::Serialize (std::shared_ptr<kurento::EndOfStream> &event, JsonSerializer &s);
};

} /* kurento */

#endif /*  __END_OF_STREAM_HPP__ */
