/* Autogenerated with kurento-module-creator */

#ifndef __HTTP_ENDPOINT_INTERNAL_HPP__
#define __HTTP_ENDPOINT_INTERNAL_HPP__

#include "HttpEndpoint.hpp"

namespace kurento
{
class JsonSerializer;
}

namespace kurento
{

class HttpEndpointMethodGetUrl
{
public:
  HttpEndpointMethodGetUrl() = default;
  ~HttpEndpointMethodGetUrl() = default;

  std::string invoke (std::shared_ptr<HttpEndpoint> obj);
  void Serialize (JsonSerializer &serializer);

};

} /* kurento */

#endif /*  __HTTP_ENDPOINT_INTERNAL_HPP__ */
