/* Autogenerated with kurento-module-creator */

#include <iostream>
#include "HttpEndpointInternal.hpp"
#include <KurentoException.hpp>
#include <jsonrpc/JsonSerializer.hpp>

namespace kurento
{

std::string HttpEndpointMethodGetUrl::invoke (std::shared_ptr<HttpEndpoint> obj)
{
  if (!obj) {
    throw KurentoException (MEDIA_OBJECT_NOT_FOUND, "Invalid object while invoking method HttpEndpoint::getUrl");
  }

  return obj->getUrl ();
}

void HttpEndpointMethodGetUrl::Serialize (kurento::JsonSerializer &s)
{
  if (s.IsWriter) {
  } else {
    if (!s.JsonValue.isNull () && !s.JsonValue.isObject ()) {
      throw KurentoException (MARSHALL_ERROR,
                              "'operationParams' should be an object");
    }

  }
}

} /* kurento */
