/* Autogenerated with kurento-module-creator */

#include "HttpPostEndpoint.hpp"
#include <mutex>

namespace kurento
{

static std::vector<std::string> hierarchyHttpPostEndpoint;
std::once_flag initFlagHttpPostEndpoint;

static void
initHierarchy ()
{
  hierarchyHttpPostEndpoint.emplace_back("kurento.HttpEndpoint");
  hierarchyHttpPostEndpoint.emplace_back("kurento.SessionEndpoint");
  hierarchyHttpPostEndpoint.emplace_back("kurento.Endpoint");
  hierarchyHttpPostEndpoint.emplace_back("kurento.MediaElement");
  hierarchyHttpPostEndpoint.emplace_back("kurento.MediaObject");
}

const std::vector<std::string> &
HttpPostEndpoint::getHierarchy () const
{
  std::call_once (initFlagHttpPostEndpoint,initHierarchy);
  return hierarchyHttpPostEndpoint;
}

const std::string&
HttpPostEndpoint::getType () const {
  static std::string typeName = "HttpPostEndpoint";

  return typeName;
}

const std::string&
HttpPostEndpoint::getQualifiedType () const {
  static std::string qualifiedTypeName = getModule() + "." + getType();

  return qualifiedTypeName;
}

const std::string&
HttpPostEndpoint::getModule () const {
  static std::string moduleName =  "kurento";

  return moduleName;
}

} /* kurento */
