/* Autogenerated with kurento-module-creator */

#ifndef __HTTP_ENDPOINT_HPP__
#define __HTTP_ENDPOINT_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "SessionEndpoint.hpp"

namespace kurento
{
class HttpEndpoint;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::HttpEndpoint> &object, JsonSerializer &serializer);
}

namespace kurento
{
class HttpEndpoint : public virtual SessionEndpoint
{

public:
  HttpEndpoint() = default;
  ~HttpEndpoint() override = default;


  virtual std::string getUrl () = 0;

  const std::string &getType() const override;
  const std::string &getQualifiedType() const override;
  const std::string &getModule() const override;
  const std::vector<std::string> &getHierarchy() const override;

  void Serialize(JsonSerializer &serializer) override = 0;

};

} /* kurento */

#endif /*  __HTTP_ENDPOINT_HPP__ */
