/* Autogenerated with kurento-module-creator */

#include "IceCandidatePair.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

namespace kurento
{

void IceCandidatePair::Serialize (JsonSerializer &s)
{

  if (s.IsWriter) {
    s.JsonValue["__type__"] = "IceCandidatePair";
    s.JsonValue["__module__"] = "kurento";

    s.SerializeNVP (streamID);

    s.SerializeNVP (componentID);

    s.SerializeNVP (localCandidate);

    s.SerializeNVP (remoteCandidate);

  } else {
    if (!s.JsonValue.isMember ("streamID") || !s.JsonValue["streamID"].isConvertibleTo (Json::ValueType::stringValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'streamID' property should be a string");
    }

    s.SerializeNVP (streamID);

    if (!s.JsonValue.isMember ("componentID") || !s.JsonValue["componentID"].isConvertibleTo (Json::ValueType::intValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'componentID' property should be a integer");
    }

    s.SerializeNVP (componentID);

    if (!s.JsonValue.isMember ("localCandidate") || !s.JsonValue["localCandidate"].isConvertibleTo (Json::ValueType::stringValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'localCandidate' property should be a string");
    }

    s.SerializeNVP (localCandidate);

    if (!s.JsonValue.isMember ("remoteCandidate") || !s.JsonValue["remoteCandidate"].isConvertibleTo (Json::ValueType::stringValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'remoteCandidate' property should be a string");
    }

    s.SerializeNVP (remoteCandidate);

  }
}

} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::IceCandidatePair> &object, JsonSerializer &s)
{
  if (!s.IsWriter && !object) {
    if (!s.JsonValue.isMember ("__type__") || !s.JsonValue["__type__"].isConvertibleTo (Json::ValueType::stringValue) || !s.JsonValue.isMember ("__module__") || !s.JsonValue["__module__"].isConvertibleTo (Json::ValueType::stringValue)) {
      object.reset (new kurento::IceCandidatePair() );
    } else {
      auto ptr = kurento::RegisterParent::createRegister (s.JsonValue["__module__"].asString () + "." + s.JsonValue["__type__"].asString ());

      if (!ptr) {
        throw KurentoException (UNEXPECTED_ERROR,
                                "Type " + s.JsonValue["__type__"].asString () + " does not exist in module " + s.JsonValue["__module__"].asString ());
      }

      object.reset (dynamic_cast <kurento::IceCandidatePair*> (ptr));

      if (!object) {
        delete ptr;
        throw KurentoException (UNEXPECTED_ERROR, "Type " + s.JsonValue["__type__"].asString () + " is not compatible");
      }
    }
  }

  if (object) {
    object->Serialize (s);
  }
}

} /* kurento */