/* Autogenerated with kurento-module-creator */

#include "IceComponentState.hpp"
#include "IceConnection.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

namespace kurento
{

void IceConnection::Serialize (JsonSerializer &s)
{

  if (s.IsWriter) {
    s.JsonValue["__type__"] = "IceConnection";
    s.JsonValue["__module__"] = "kurento";

    s.SerializeNVP (streamId);

    s.SerializeNVP (componentId);

    s.SerializeNVP (state);

  } else {
    if (!s.JsonValue.isMember ("streamId") || !s.JsonValue["streamId"].isConvertibleTo (Json::ValueType::stringValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'streamId' property should be a string");
    }

    s.SerializeNVP (streamId);

    if (!s.JsonValue.isMember ("componentId") || !s.JsonValue["componentId"].isConvertibleTo (Json::ValueType::intValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'componentId' property should be a integer");
    }

    s.SerializeNVP (componentId);

    if (!s.JsonValue.isMember ("state") || !s.JsonValue["state"].isConvertibleTo (Json::ValueType::stringValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'state' property should be a string");
    }

    s.SerializeNVP (state);

  }
}

} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::IceConnection> &object, JsonSerializer &s)
{
  if (!s.IsWriter && !object) {
    if (!s.JsonValue.isMember ("__type__") || !s.JsonValue["__type__"].isConvertibleTo (Json::ValueType::stringValue) || !s.JsonValue.isMember ("__module__") || !s.JsonValue["__module__"].isConvertibleTo (Json::ValueType::stringValue)) {
      object.reset (new kurento::IceConnection() );
    } else {
      auto ptr = kurento::RegisterParent::createRegister (s.JsonValue["__module__"].asString () + "." + s.JsonValue["__type__"].asString ());

      if (!ptr) {
        throw KurentoException (UNEXPECTED_ERROR,
                                "Type " + s.JsonValue["__type__"].asString () + " does not exist in module " + s.JsonValue["__module__"].asString ());
      }

      object.reset (dynamic_cast <kurento::IceConnection*> (ptr));

      if (!object) {
        delete ptr;
        throw KurentoException (UNEXPECTED_ERROR, "Type " + s.JsonValue["__type__"].asString () + " is not compatible");
      }
    }
  }

  if (object) {
    object->Serialize (s);
  }
}

} /* kurento */