/* Autogenerated with kurento-module-creator */

#include "IceCandidate.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

namespace kurento
{

void IceCandidate::Serialize (JsonSerializer &s)
{

  if (s.IsWriter) {
    s.JsonValue["__type__"] = "IceCandidate";
    s.JsonValue["__module__"] = "kurento";

    s.SerializeNVP (candidate);

    s.SerializeNVP (sdpMid);

    s.SerializeNVP (sdpMLineIndex);

  } else {
    if (!s.JsonValue.isMember ("candidate") || !s.JsonValue["candidate"].isConvertibleTo (Json::ValueType::stringValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'candidate' property should be a string");
    }

    s.SerializeNVP (candidate);

    if (!s.JsonValue.isMember ("sdpMid") || !s.JsonValue["sdpMid"].isConvertibleTo (Json::ValueType::stringValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'sdpMid' property should be a string");
    }

    s.SerializeNVP (sdpMid);

    if (!s.JsonValue.isMember ("sdpMLineIndex") || !s.JsonValue["sdpMLineIndex"].isConvertibleTo (Json::ValueType::intValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'sdpMLineIndex' property should be a integer");
    }

    s.SerializeNVP (sdpMLineIndex);

  }
}

} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::IceCandidate> &object, JsonSerializer &s)
{
  if (!s.IsWriter && !object) {
    if (!s.JsonValue.isMember ("__type__") || !s.JsonValue["__type__"].isConvertibleTo (Json::ValueType::stringValue) || !s.JsonValue.isMember ("__module__") || !s.JsonValue["__module__"].isConvertibleTo (Json::ValueType::stringValue)) {
      object.reset (new kurento::IceCandidate() );
    } else {
      auto ptr = kurento::RegisterParent::createRegister (s.JsonValue["__module__"].asString () + "." + s.JsonValue["__type__"].asString ());

      if (!ptr) {
        throw KurentoException (UNEXPECTED_ERROR,
                                "Type " + s.JsonValue["__type__"].asString () + " does not exist in module " + s.JsonValue["__module__"].asString ());
      }

      object.reset (dynamic_cast <kurento::IceCandidate*> (ptr));

      if (!object) {
        delete ptr;
        throw KurentoException (UNEXPECTED_ERROR, "Type " + s.JsonValue["__type__"].asString () + " is not compatible");
      }
    }
  }

  if (object) {
    object->Serialize (s);
  }
}

} /* kurento */