/* Autogenerated with kurento-module-creator */

#include "IceGatheringDone.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <chrono>
#include <ctime>
#include <string>

namespace kurento
{

void
IceGatheringDone::Serialize (JsonSerializer &s)
{
  Media::Serialize (s);

}

} /* kurento */

namespace kurento
{

void Serialize (std::shared_ptr<kurento::IceGatheringDone> &event, JsonSerializer &s)
{
  if (!s.IsWriter && !event) {
    event.reset (new kurento::IceGatheringDone() );
  }

  if (event) {
    event->Serialize (s);
  }
}

} /* kurento */
