/* Autogenerated with kurento-module-creator */

#ifndef __ICE_GATHERING_DONE_HPP__
#define __ICE_GATHERING_DONE_HPP__

#include <json/json.h>
#include <memory>
#include "Media.hpp"

namespace kurento
{
class IceGatheringDone;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::IceGatheringDone> &object, JsonSerializer &s);
}


namespace kurento
{

class IceGatheringDone : public Media
{

public:

  IceGatheringDone (std::shared_ptr<MediaObject> source, const std::string &type) : Media (source, type) {
  };

  IceGatheringDone (const IceGatheringDone &copy) : Media (copy) {
  };

  IceGatheringDone (const Json::Value &value);

  static std::string getName() {
    return "IceGatheringDone";
  }

  void Serialize (JsonSerializer &s) override;

protected:

  IceGatheringDone() = default;

private:

  friend void kurento::Serialize (std::shared_ptr<kurento::IceGatheringDone> &event, JsonSerializer &s);
};

} /* kurento */

#endif /*  __ICE_GATHERING_DONE_HPP__ */
