/* Autogenerated with kurento-module-creator */

#include "Mixer.hpp"
#include <mutex>

namespace kurento
{

static std::vector<std::string> hierarchyMixer;
std::once_flag initFlagMixer;

static void
initHierarchy ()
{
  hierarchyMixer.emplace_back("kurento.Hub");
  hierarchyMixer.emplace_back("kurento.MediaObject");
}

const std::vector<std::string> &
Mixer::getHierarchy () const
{
  std::call_once (initFlagMixer,initHierarchy);
  return hierarchyMixer;
}

const std::string&
Mixer::getType () const {
  static std::string typeName = "Mixer";

  return typeName;
}

const std::string&
Mixer::getQualifiedType () const {
  static std::string qualifiedTypeName = getModule() + "." + getType();

  return qualifiedTypeName;
}

const std::string&
Mixer::getModule () const {
  static std::string moduleName =  "kurento";

  return moduleName;
}

} /* kurento */
