/* Autogenerated with kurento-module-creator */

#include "NewCandidatePairSelected.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include "IceCandidatePair.hpp"
#include <chrono>
#include <ctime>
#include <string>

namespace kurento
{

void
NewCandidatePairSelected::Serialize (JsonSerializer &s)
{
  Media::Serialize (s);

  s.SerializeNVP (candidatePair);
}

} /* kurento */

namespace kurento
{

void Serialize (std::shared_ptr<kurento::NewCandidatePairSelected> &event, JsonSerializer &s)
{
  if (!s.IsWriter && !event) {
    event.reset (new kurento::NewCandidatePairSelected() );
  }

  if (event) {
    event->Serialize (s);
  }
}

} /* kurento */
