/* Autogenerated with kurento-module-creator */

#ifndef __ON_ICE_GATHERING_DONE_HPP__
#define __ON_ICE_GATHERING_DONE_HPP__

#include <json/json.h>
#include <memory>
#include "Media.hpp"

namespace kurento
{
class OnIceGatheringDone;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::OnIceGatheringDone> &object, JsonSerializer &s);
}


namespace kurento
{

class OnIceGatheringDone : public Media
{

public:

  OnIceGatheringDone (std::shared_ptr<MediaObject> source, const std::string &type) : Media (source, type) {
  };

  OnIceGatheringDone (const OnIceGatheringDone &copy) : Media (copy) {
  };

  OnIceGatheringDone (const Json::Value &value);

  static std::string getName() {
    return "OnIceGatheringDone";
  }

  void Serialize (JsonSerializer &s) override;

protected:

  OnIceGatheringDone() = default;

private:

  friend void kurento::Serialize (std::shared_ptr<kurento::OnIceGatheringDone> &event, JsonSerializer &s);
};

} /* kurento */

#endif /*  __ON_ICE_GATHERING_DONE_HPP__ */
