/* Autogenerated with kurento-module-creator */

#include "OnIceComponentStateChanged.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include "IceComponentState.hpp"
#include <chrono>
#include <ctime>
#include <string>

namespace kurento
{

void
OnIceComponentStateChanged::Serialize (JsonSerializer &s)
{
  Media::Serialize (s);

  s.SerializeNVP (streamId);
  s.SerializeNVP (componentId);
  s.SerializeNVP (state);
}

} /* kurento */

namespace kurento
{

void Serialize (std::shared_ptr<kurento::OnIceComponentStateChanged> &event, JsonSerializer &s)
{
  if (!s.IsWriter && !event) {
    event.reset (new kurento::OnIceComponentStateChanged() );
  }

  if (event) {
    event->Serialize (s);
  }
}

} /* kurento */
