/* Autogenerated with kurento-module-creator */

#ifndef __ON_ICE_CANDIDATE_HPP__
#define __ON_ICE_CANDIDATE_HPP__

#include <json/json.h>
#include <memory>
#include "Media.hpp"

namespace kurento
{
class OnIceCandidate;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::OnIceCandidate> &object, JsonSerializer &s);
}


namespace kurento
{
class IceCandidate;
} /* kurento */

namespace kurento
{
class IceCandidate;

class OnIceCandidate : public Media
{

public:

  OnIceCandidate (std::shared_ptr<MediaObject> source, const std::string &type, std::shared_ptr<IceCandidate> candidate) : Media (source, type) {
      this->candidate = candidate;
  };

  OnIceCandidate (const OnIceCandidate &copy) : Media (copy) {
      this->candidate = copy.candidate;
  };

  OnIceCandidate (const Json::Value &value);

  virtual void setCandidate (std::shared_ptr<IceCandidate> candidate) {
    this->candidate = candidate;
  };

  virtual std::shared_ptr<IceCandidate> getCandidate () {
    return candidate;
  };

  static std::string getName() {
    return "OnIceCandidate";
  }

  void Serialize (JsonSerializer &s) override;

protected:

  OnIceCandidate() = default;

private:
  std::shared_ptr<IceCandidate> candidate;

  friend void kurento::Serialize (std::shared_ptr<kurento::OnIceCandidate> &event, JsonSerializer &s);
};

} /* kurento */

#endif /*  __ON_ICE_CANDIDATE_HPP__ */
