/* Autogenerated with kurento-module-creator */

#ifndef __PAUSED_HPP__
#define __PAUSED_HPP__

#include <json/json.h>
#include <memory>
#include "Media.hpp"

namespace kurento
{
class Paused;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::Paused> &object, JsonSerializer &s);
}


namespace kurento
{

class Paused : public Media
{

public:

  Paused (std::shared_ptr<MediaObject> source, const std::string &type) : Media (source, type) {
  };

  Paused (const Paused &copy) : Media (copy) {
  };

  Paused (const Json::Value &value);

  static std::string getName() {
    return "Paused";
  }

  void Serialize (JsonSerializer &s) override;

protected:

  Paused() = default;

private:

  friend void kurento::Serialize (std::shared_ptr<kurento::Paused> &event, JsonSerializer &s);
};

} /* kurento */

#endif /*  __PAUSED_HPP__ */
