/* Autogenerated with kurento-module-creator */

#include "PlayerEndpoint.hpp"
#include <mutex>

namespace kurento
{

static std::vector<std::string> hierarchyPlayerEndpoint;
std::once_flag initFlagPlayerEndpoint;

static void
initHierarchy ()
{
  hierarchyPlayerEndpoint.emplace_back("kurento.UriEndpoint");
  hierarchyPlayerEndpoint.emplace_back("kurento.Endpoint");
  hierarchyPlayerEndpoint.emplace_back("kurento.MediaElement");
  hierarchyPlayerEndpoint.emplace_back("kurento.MediaObject");
}

const std::vector<std::string> &
PlayerEndpoint::getHierarchy () const
{
  std::call_once (initFlagPlayerEndpoint,initHierarchy);
  return hierarchyPlayerEndpoint;
}

const std::string&
PlayerEndpoint::getType () const {
  static std::string typeName = "PlayerEndpoint";

  return typeName;
}

const std::string&
PlayerEndpoint::getQualifiedType () const {
  static std::string qualifiedTypeName = getModule() + "." + getType();

  return qualifiedTypeName;
}

const std::string&
PlayerEndpoint::getModule () const {
  static std::string moduleName =  "kurento";

  return moduleName;
}

} /* kurento */
