/* Autogenerated with kurento-module-creator */

#include <iostream>
#include "PlayerEndpointInternal.hpp"
#include <KurentoException.hpp>
#include <jsonrpc/JsonSerializer.hpp>
#include "MediaPipeline.hpp"
#include "VideoInfo.hpp"

namespace kurento
{

void PlayerEndpointMethodPlay::invoke (std::shared_ptr<PlayerEndpoint> obj)
{
  if (!obj) {
    throw KurentoException (MEDIA_OBJECT_NOT_FOUND, "Invalid object while invoking method PlayerEndpoint::play");
  }

  return obj->play ();
}

void PlayerEndpointMethodPlay::Serialize (kurento::JsonSerializer &s)
{
  if (s.IsWriter) {
  } else {
    if (!s.JsonValue.isNull () && !s.JsonValue.isObject ()) {
      throw KurentoException (MARSHALL_ERROR,
                              "'operationParams' should be an object");
    }

  }
}

std::shared_ptr<MediaPipeline> PlayerEndpointConstructor::getMediaPipeline ()
{
  return mediaPipeline;
}

std::string PlayerEndpointConstructor::getUri ()
{
  return uri;
}

bool PlayerEndpointConstructor::getUseEncodedMedia ()
{
  if (!__isSetUseEncodedMedia && !__isSetDefaultUseEncodedMedia) {
    try {
      kurento::JsonSerializer s (false);
      Json::Reader reader;
      std::string defaultValue = "false";

      reader.parse (defaultValue, s.JsonValue["useEncodedMedia"]);
      s.SerializeNVP (useEncodedMedia);
      __isSetDefaultUseEncodedMedia = true;
    } catch (std::exception &e) {
      std::cerr << "Unexpected exception deserializing default value useEncodedMedia of PlayerEndpoint constructor, check your module: " << e.what() << std::endl;
    }
  }

  return useEncodedMedia;
}

int PlayerEndpointConstructor::getNetworkCache ()
{
  if (!__isSetNetworkCache && !__isSetDefaultNetworkCache) {
    try {
      kurento::JsonSerializer s (false);
      Json::Reader reader;
      std::string defaultValue = "2000";

      reader.parse (defaultValue, s.JsonValue["networkCache"]);
      s.SerializeNVP (networkCache);
      __isSetDefaultNetworkCache = true;
    } catch (std::exception &e) {
      std::cerr << "Unexpected exception deserializing default value networkCache of PlayerEndpoint constructor, check your module: " << e.what() << std::endl;
    }
  }

  return networkCache;
}

void PlayerEndpointConstructor::Serialize (kurento::JsonSerializer &s)
{
  if (s.IsWriter) {
    s.SerializeNVP (mediaPipeline);

    s.SerializeNVP (uri);

    if (__isSetUseEncodedMedia) {
      s.SerializeNVP (useEncodedMedia);
    }

    if (__isSetNetworkCache) {
      s.SerializeNVP (networkCache);
    }

  } else {
    if (s.JsonValue.isNull ()) {
      throw KurentoException (MARSHALL_ERROR,
                              "'constructorParams' is required");
    } else if (!s.JsonValue.isObject ()){
      throw KurentoException (MARSHALL_ERROR,
                              "'constructorParams' should be an object");
    }

    if (!s.JsonValue.isMember ("mediaPipeline") || !s.JsonValue["mediaPipeline"].isConvertibleTo (Json::ValueType::stringValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'mediaPipeline' parameter should be a string");
    }

    s.SerializeNVP (mediaPipeline);

    if (!s.JsonValue.isMember ("uri") || !s.JsonValue["uri"].isConvertibleTo (Json::ValueType::stringValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'uri' parameter should be a string");
    }

    s.SerializeNVP (uri);

    if (s.JsonValue.isMember ("useEncodedMedia") ) {
      if (s.JsonValue["useEncodedMedia"].isConvertibleTo (Json::ValueType::booleanValue) ) {
        __isSetUseEncodedMedia = true;
        s.SerializeNVP (useEncodedMedia);
      } else {
        throw KurentoException (MARSHALL_ERROR,
                                "'useEncodedMedia' parameter should be a boolean");
      }
    }

    if (s.JsonValue.isMember ("networkCache") ) {
      if (s.JsonValue["networkCache"].isConvertibleTo (Json::ValueType::intValue) ) {
        __isSetNetworkCache = true;
        s.SerializeNVP (networkCache);
      } else {
        throw KurentoException (MARSHALL_ERROR,
                                "'networkCache' parameter should be a integer");
      }
    }

  }
}

} /* kurento */
