/* Autogenerated with kurento-module-creator */

#ifndef __RECORDER_ENDPOINT_HPP__
#define __RECORDER_ENDPOINT_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "UriEndpoint.hpp"
#include "Recording.hpp"
#include "Paused.hpp"
#include "Stopped.hpp"
#include <sigc++/sigc++.h>

namespace kurento
{
class RecorderEndpoint;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::RecorderEndpoint> &object, JsonSerializer &serializer);
}

namespace kurento
{
class MediaPipeline;
class MediaProfileSpecType;
} /* kurento */

namespace kurento
{
class RecorderEndpoint : public virtual UriEndpoint
{

public:
  RecorderEndpoint() = default;
  ~RecorderEndpoint() override = default;


  virtual void record () = 0;
  virtual void stopAndWait () = 0;

  const std::string &getType() const override;
  const std::string &getQualifiedType() const override;
  const std::string &getModule() const override;
  const std::vector<std::string> &getHierarchy() const override;

  void Serialize(JsonSerializer &serializer) override = 0;

};

} /* kurento */

#endif /*  __RECORDER_ENDPOINT_HPP__ */
