/* Autogenerated with kurento-module-creator */

#ifndef __RECORDING_HPP__
#define __RECORDING_HPP__

#include <json/json.h>
#include <memory>
#include "Media.hpp"

namespace kurento
{
class Recording;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::Recording> &object, JsonSerializer &s);
}


namespace kurento
{

class Recording : public Media
{

public:

  Recording (std::shared_ptr<MediaObject> source, const std::string &type) : Media (source, type) {
  };

  Recording (const Recording &copy) : Media (copy) {
  };

  Recording (const Json::Value &value);

  static std::string getName() {
    return "Recording";
  }

  void Serialize (JsonSerializer &s) override;

protected:

  Recording() = default;

private:

  friend void kurento::Serialize (std::shared_ptr<kurento::Recording> &event, JsonSerializer &s);
};

} /* kurento */

#endif /*  __RECORDING_HPP__ */
