/* Autogenerated with kurento-module-creator */

#include "RecorderEndpoint.hpp"
#include <mutex>

namespace kurento
{

static std::vector<std::string> hierarchyRecorderEndpoint;
std::once_flag initFlagRecorderEndpoint;

static void
initHierarchy ()
{
  hierarchyRecorderEndpoint.emplace_back("kurento.UriEndpoint");
  hierarchyRecorderEndpoint.emplace_back("kurento.Endpoint");
  hierarchyRecorderEndpoint.emplace_back("kurento.MediaElement");
  hierarchyRecorderEndpoint.emplace_back("kurento.MediaObject");
}

const std::vector<std::string> &
RecorderEndpoint::getHierarchy () const
{
  std::call_once (initFlagRecorderEndpoint,initHierarchy);
  return hierarchyRecorderEndpoint;
}

const std::string&
RecorderEndpoint::getType () const {
  static std::string typeName = "RecorderEndpoint";

  return typeName;
}

const std::string&
RecorderEndpoint::getQualifiedType () const {
  static std::string qualifiedTypeName = getModule() + "." + getType();

  return qualifiedTypeName;
}

const std::string&
RecorderEndpoint::getModule () const {
  static std::string moduleName =  "kurento";

  return moduleName;
}

} /* kurento */
