/* Autogenerated with kurento-module-creator */

#include "RtpEndpoint.hpp"
#include <mutex>

namespace kurento
{

static std::vector<std::string> hierarchyRtpEndpoint;
std::once_flag initFlagRtpEndpoint;

static void
initHierarchy ()
{
  hierarchyRtpEndpoint.emplace_back("kurento.BaseRtpEndpoint");
  hierarchyRtpEndpoint.emplace_back("kurento.SdpEndpoint");
  hierarchyRtpEndpoint.emplace_back("kurento.SessionEndpoint");
  hierarchyRtpEndpoint.emplace_back("kurento.Endpoint");
  hierarchyRtpEndpoint.emplace_back("kurento.MediaElement");
  hierarchyRtpEndpoint.emplace_back("kurento.MediaObject");
}

const std::vector<std::string> &
RtpEndpoint::getHierarchy () const
{
  std::call_once (initFlagRtpEndpoint,initHierarchy);
  return hierarchyRtpEndpoint;
}

const std::string&
RtpEndpoint::getType () const {
  static std::string typeName = "RtpEndpoint";

  return typeName;
}

const std::string&
RtpEndpoint::getQualifiedType () const {
  static std::string qualifiedTypeName = getModule() + "." + getType();

  return qualifiedTypeName;
}

const std::string&
RtpEndpoint::getModule () const {
  static std::string moduleName =  "kurento";

  return moduleName;
}

} /* kurento */
