/* Autogenerated with kurento-module-creator */

#include "CryptoSuite.hpp"
#include "SDES.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

namespace kurento
{

void SDES::Serialize (JsonSerializer &s)
{

  if (s.IsWriter) {
    s.JsonValue["__type__"] = "SDES";
    s.JsonValue["__module__"] = "kurento";

    if (__isSetKey) {
      s.SerializeNVP (key);
    }

    if (__isSetKeyBase64) {
      s.SerializeNVP (keyBase64);
    }

    if (__isSetCrypto) {
      s.SerializeNVP (crypto);
    }

  } else {
    if (s.JsonValue.isMember ("key") ) {
      if (s.JsonValue["key"].isConvertibleTo (Json::ValueType::stringValue) ) {
        __isSetKey = true;
        s.SerializeNVP (key);
      } else {
        throw KurentoException (MARSHALL_ERROR,
                                "'key' property should be a string");
      }
    }

    if (s.JsonValue.isMember ("keyBase64") ) {
      if (s.JsonValue["keyBase64"].isConvertibleTo (Json::ValueType::stringValue) ) {
        __isSetKeyBase64 = true;
        s.SerializeNVP (keyBase64);
      } else {
        throw KurentoException (MARSHALL_ERROR,
                                "'keyBase64' property should be a string");
      }
    }

    if (s.JsonValue.isMember ("crypto") ) {
      if (s.JsonValue["crypto"].isConvertibleTo (Json::ValueType::stringValue) ) {
        __isSetCrypto = true;
        s.SerializeNVP (crypto);
      } else {
        throw KurentoException (MARSHALL_ERROR,
                                "'crypto' property should be a string");
      }
    }

  }
}

} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::SDES> &object, JsonSerializer &s)
{
  if (!s.IsWriter && !object) {
    if (!s.JsonValue.isMember ("__type__") || !s.JsonValue["__type__"].isConvertibleTo (Json::ValueType::stringValue) || !s.JsonValue.isMember ("__module__") || !s.JsonValue["__module__"].isConvertibleTo (Json::ValueType::stringValue)) {
      object.reset (new kurento::SDES() );
    } else {
      auto ptr = kurento::RegisterParent::createRegister (s.JsonValue["__module__"].asString () + "." + s.JsonValue["__type__"].asString ());

      if (!ptr) {
        throw KurentoException (UNEXPECTED_ERROR,
                                "Type " + s.JsonValue["__type__"].asString () + " does not exist in module " + s.JsonValue["__module__"].asString ());
      }

      object.reset (dynamic_cast <kurento::SDES*> (ptr));

      if (!object) {
        delete ptr;
        throw KurentoException (UNEXPECTED_ERROR, "Type " + s.JsonValue["__type__"].asString () + " is not compatible");
      }
    }
  }

  if (object) {
    object->Serialize (s);
  }
}

} /* kurento */