/* Autogenerated with kurento-module-creator */

#ifndef __STOPPED_HPP__
#define __STOPPED_HPP__

#include <json/json.h>
#include <memory>
#include "Media.hpp"

namespace kurento
{
class Stopped;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::Stopped> &object, JsonSerializer &s);
}


namespace kurento
{

class Stopped : public Media
{

public:

  Stopped (std::shared_ptr<MediaObject> source, const std::string &type) : Media (source, type) {
  };

  Stopped (const Stopped &copy) : Media (copy) {
  };

  Stopped (const Json::Value &value);

  static std::string getName() {
    return "Stopped";
  }

  void Serialize (JsonSerializer &s) override;

protected:

  Stopped() = default;

private:

  friend void kurento::Serialize (std::shared_ptr<kurento::Stopped> &event, JsonSerializer &s);
};

} /* kurento */

#endif /*  __STOPPED_HPP__ */
