/* Autogenerated with kurento-module-creator */

#ifndef __VIDEO_INFO_HPP__
#define __VIDEO_INFO_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <RegisterParent.hpp>


namespace kurento
{
class VideoInfo;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::VideoInfo> &object, JsonSerializer &s);
} /* kurento */

namespace kurento
{

class VideoInfo : public RegisterParent 
{

public:

  VideoInfo (bool isSeekable, int64_t seekableInit, int64_t seekableEnd, int64_t duration) {
    this->isSeekable = isSeekable;
    this->seekableInit = seekableInit;
    this->seekableEnd = seekableEnd;
    this->duration = duration;
  };

  void setIsSeekable (bool isSeekable) {
    this->isSeekable = isSeekable;
  };

  bool getIsSeekable () {
    return isSeekable;
  };

  void setSeekableInit (int64_t seekableInit) {
    this->seekableInit = seekableInit;
  };

  int64_t getSeekableInit () {
    return seekableInit;
  };

  void setSeekableEnd (int64_t seekableEnd) {
    this->seekableEnd = seekableEnd;
  };

  int64_t getSeekableEnd () {
    return seekableEnd;
  };

  void setDuration (int64_t duration) {
    this->duration = duration;
  };

  int64_t getDuration () {
    return duration;
  };

  virtual void Serialize (JsonSerializer &s);

  static void registerType () {
    std::function<RegisterParent*(void)> func =
        [] () {

      return new VideoInfo ();

    };

    RegisterParent::registerType ("kurento.VideoInfo", func);
  }

protected:

  VideoInfo() = default;

private:

  bool isSeekable;
  int64_t seekableInit;
  int64_t seekableEnd;
  int64_t duration;

  friend void kurento::Serialize (std::shared_ptr<kurento::VideoInfo> &object, JsonSerializer &s);

};

} /* kurento */

#endif /*  __VIDEO_INFO_HPP__ */
