/* Autogenerated with kurento-module-creator */

#include "VideoInfo.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

namespace kurento
{

void VideoInfo::Serialize (JsonSerializer &s)
{

  if (s.IsWriter) {
    s.JsonValue["__type__"] = "VideoInfo";
    s.JsonValue["__module__"] = "kurento";

    s.SerializeNVP (isSeekable);

    s.SerializeNVP (seekableInit);

    s.SerializeNVP (seekableEnd);

    s.SerializeNVP (duration);

  } else {
    if (!s.JsonValue.isMember ("isSeekable") || !s.JsonValue["isSeekable"].isConvertibleTo (Json::ValueType::booleanValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'isSeekable' property should be a boolean");
    }

    s.SerializeNVP (isSeekable);

    if (!s.JsonValue.isMember ("seekableInit") || !s.JsonValue["seekableInit"].isConvertibleTo (Json::ValueType::int64Value) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'seekableInit' property should be a int64");
    }

    s.SerializeNVP (seekableInit);

    if (!s.JsonValue.isMember ("seekableEnd") || !s.JsonValue["seekableEnd"].isConvertibleTo (Json::ValueType::int64Value) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'seekableEnd' property should be a int64");
    }

    s.SerializeNVP (seekableEnd);

    if (!s.JsonValue.isMember ("duration") || !s.JsonValue["duration"].isConvertibleTo (Json::ValueType::int64Value) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'duration' property should be a int64");
    }

    s.SerializeNVP (duration);

  }
}

} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::VideoInfo> &object, JsonSerializer &s)
{
  if (!s.IsWriter && !object) {
    if (!s.JsonValue.isMember ("__type__") || !s.JsonValue["__type__"].isConvertibleTo (Json::ValueType::stringValue) || !s.JsonValue.isMember ("__module__") || !s.JsonValue["__module__"].isConvertibleTo (Json::ValueType::stringValue)) {
      object.reset (new kurento::VideoInfo() );
    } else {
      auto ptr = kurento::RegisterParent::createRegister (s.JsonValue["__module__"].asString () + "." + s.JsonValue["__type__"].asString ());

      if (!ptr) {
        throw KurentoException (UNEXPECTED_ERROR,
                                "Type " + s.JsonValue["__type__"].asString () + " does not exist in module " + s.JsonValue["__module__"].asString ());
      }

      object.reset (dynamic_cast <kurento::VideoInfo*> (ptr));

      if (!object) {
        delete ptr;
        throw KurentoException (UNEXPECTED_ERROR, "Type " + s.JsonValue["__type__"].asString () + " is not compatible");
      }
    }
  }

  if (object) {
    object->Serialize (s);
  }
}

} /* kurento */