/* Autogenerated with kurento-module-creator */

#include "WebRtcEndpoint.hpp"
#include <mutex>

namespace kurento
{

static std::vector<std::string> hierarchyWebRtcEndpoint;
std::once_flag initFlagWebRtcEndpoint;

static void
initHierarchy ()
{
  hierarchyWebRtcEndpoint.emplace_back("kurento.BaseRtpEndpoint");
  hierarchyWebRtcEndpoint.emplace_back("kurento.SdpEndpoint");
  hierarchyWebRtcEndpoint.emplace_back("kurento.SessionEndpoint");
  hierarchyWebRtcEndpoint.emplace_back("kurento.Endpoint");
  hierarchyWebRtcEndpoint.emplace_back("kurento.MediaElement");
  hierarchyWebRtcEndpoint.emplace_back("kurento.MediaObject");
}

const std::vector<std::string> &
WebRtcEndpoint::getHierarchy () const
{
  std::call_once (initFlagWebRtcEndpoint,initHierarchy);
  return hierarchyWebRtcEndpoint;
}

const std::string&
WebRtcEndpoint::getType () const {
  static std::string typeName = "WebRtcEndpoint";

  return typeName;
}

const std::string&
WebRtcEndpoint::getQualifiedType () const {
  static std::string qualifiedTypeName = getModule() + "." + getType();

  return qualifiedTypeName;
}

const std::string&
WebRtcEndpoint::getModule () const {
  static std::string moduleName =  "kurento";

  return moduleName;
}

} /* kurento */
